### ISSUE TITLE
[Feature request] CLI status option

### ISSUE THREAD

**Issue by unknown--** [Windscribe/Desktop-App#111]
Could you please consider adding a 'status' option to the CLI so the user can check if Windscribe is connected and if so, to which location.
Currently doing so from the command line means checking network adapters which isn't overly reliable.
Thanks.

**Comment by bernerdad** [comment]
Hi.  Yes, we can indeed consider adding this feature.  Can you provide some more detail?  What would you expect the new `status` command to print out when the app is connected or disconnected?

**Comment by unknown--** [comment]
A simple "Connected" or "Disconnected" would suffice but if possible it would be nice to know the selected location alongside of it. Examples:
Connected: London - Crumpets (GB)
Disconnected: Frankfurt - Castle (DE)

**Comment by bernerdad** [comment]
Hi.  We've implemented this feature request and it will be available in our next guinea pig build (v2.9.2), which will be available in the first week of January.  Cheers, and happy holidays!

**Comment by bernerdad** [comment]
Hi.  This feature is now available in the v2.9.2 guinea pig build.
