### ISSUE TITLE
Remember window position across system reboots

### ISSUE THREAD

**Issue by ksz16** [Windscribe/Desktop-App#112]
Distro: Arch Linux + LXQt 1.30
It would be nice if the app remembered its last position on the desktop.
Currently, it appears in random places after a reboot.

**Comment by bernerdad** [comment]
Hi.  Please give our latest guinea pig build a shot and let us know if it resolves the issue for you.  Also note that Wayland does not allow us to position the app when the app is launched, but xorg does.
https://deploy.totallyacdn.com/desktop-apps/2.8.1/windscribe_2.8.1_guinea_pig_amd64.deb

**Comment by ksz16** [comment]
Unfortunately, the latest guinea pig build does not solve the problem.

Tested on:
Arch Linux
LXQt 1.4.0
xorg-server 21.1.9-1
windscribe_2.8.1_guinea_pig_x86_64.pkg.tar.zst

**Comment by bernerdad** [comment]
Drat!  Also, apologies for providing the wrong distro link above.  We'll investigate when time permits.

**Comment by bernerdad** [comment]
@ksz16 Can you let us know if the latest [release](https://github.com/Windscribe/Desktop-App/releases/tag/v2.11.11) still exhibits this behavior?  Thanks!

**Comment by ksz16** [comment]
Tested on:
Arch Linux 6.10.10-arch1-1
LXQt 2.0.0

I can confirm that in version 2.11.11 everything works correctly. Anyway, this bug has already been fixed in previous versions. Certainly in version 2.10.15 it also worked correctly. Perhaps also in version 2.9.9, but I'm not 100% sure about that.
