### ISSUE TITLE
Connection issues on ICS enabled network adapter

### ISSUE THREAD

**Issue by anfokaboom** [Windscribe/Desktop-App#113]
Windows 11 Pro x64 22H2
Windscribe 2.7.14

Perhaps Internet Connection Sharing (ICS) is considered by some obsolete, however, I have a situation that necessitates it and Windows 11 still supports it. The ICS adapter in my computer is a WLAN and when ICS is enabled, occasionally Windscribe will not connect to a VPN server. Only when I disable ICS will Windscribe connect.

I'm suspect a good reason for this exists related to LAN security, but I'm also no expert. I can work around the issue for now.

**Comment by bernerdad** [comment]
Hi.  Is this a regression in the new 2.7 app and ICS worked fine for you in the old 2.6 app?

**Comment by anfokaboom** [comment]
I don't have a clear answer for you, unfortunately. I am willing to do a barrage of tests with both versions if you wish.

**Comment by bernerdad** [comment]
Hi.  It would be most appreciated if you could let us know if the 2.6.14 app exhibits the same behavior.  Thanks!
https://deploy.totallyacdn.com/desktop-apps/2.6.14/Windscribe_2.6.14.exe

**Comment by anfokaboom** [comment]
Hopefully this helps:
https://youtu.be/XnjCTLcJtXU

**Comment by bernerdad** [comment]
Thank you for the video!  We will investigate asap.

**Comment by bernerdad** [comment]
Hi.  If you set the `Connection Mode` to `Manual` and use the `IKEv2` or `UDP` protocols, does this issue still occur?

**Comment by anfokaboom** [comment]
That worked:
https://youtu.be/rjsmWCvxkFE

**Comment by bernerdad** [comment]
Excellent that IKEv2 and UDP work for you.  I recommend using IKEv2 as it will give you similar performance (network throughput) to wireguard.

**Comment by anfokaboom** [comment]
That was my last question moving forward. It sounds like Wireguard is not compatible with ICS. It seemed like the best protocol of the bunch, but hopefully IKEv2 won't give me any issues.
