### ISSUE TITLE
[Feature] CLI should be separated from GUI

### ISSUE THREAD

**Issue by NgoHuy** [Windscribe/Desktop-App#117]
When I use cli, it always launches GUI, it annoys me. It should generate login's link and logins on other browser then uses callback instead, like NordVPN. 
Because I want to use it on my VM with no Xorg/Wayland, it refused to start.

**Comment by bernerdad** [comment]
Hi, and thank you for the feature suggestion.  We have internally discussed doing this recently, but there is currently no plan to implement this in the near future.  We will update this issue when a decision is made.

**Comment by raycekar** [comment]
+1 for this.  I prefer to use the cli without the GUI and would love to see this feature.

**Comment by valknight** [comment]
If you need a user-story internally to get this prioritised - this feels like a regression from my standpoint. I can connect using OpenVPN, but, it used to be a convenient option to just login with windscribe-cli, and, was a differentiating reason for me sticking with Windscribe.

As for a temp fix - is there an option to grab the previous version of `windscribe-cli`? Thanks :)

**Comment by bernerdad** [comment]
> If you need a user-story internally to get this prioritised - this feels like a regression from my standpoint. I can connect using OpenVPN, but, it used to be a convenient option to just login with windscribe-cli, and, was a differentiating reason for me sticking with Windscribe.
> 
> As for a temp fix - is there an option to grab the previous version of `windscribe-cli`? Thanks :)

Yes, you can download the previous Linux CLI app here: https://assets.staticnetcontent.com/desktop/linux/windscribe-cli_1.4-51_amd64.deb

**Comment by xiota** [comment]
According to the license file contained within the deb, the program is licensed under GPL2+.  Where is the source code located?

**Comment by bernerdad** [comment]
> According to the license file contained within the deb, the program is licensed under GPL2+. Where is the source code located?

Are you referring to the old windscribe-cli 1.4-51 app source code?

**Comment by xiota** [comment]
> Are you referring to the old windscribe-cli 1.4-51 app source code?

Yes.  That is the point of this issue.  That is the deb link you provided.

**Comment by cvoltorb** [comment]
+ here

**Comment by bernerdad** [comment]
> According to the license file contained within the deb, the program is licensed under GPL2+. Where is the source code located?

Apologies, I had to do some digging on this one.  The source for that old Linux CLI app was never published.

**Comment by xiota** [comment]
Is this related or different: https://github.com/Windscribe/Desktop-App/tree/master/gui/cli ?

**Comment by bernerdad** [comment]
> Is this related or different: https://github.com/Windscribe/Desktop-App/tree/master/gui/cli ?

Different.  That is the current CLI app, which interfaces with the GUI app.

**Comment by raycekar** [comment]
Why is it set up that way out of curiosity? Normally a GUI app of an application is what interfaces with the cli of a program, not the other way around far as I know

**Comment by bernerdad** [comment]
> Why is it set up that way out of curiosity? Normally a GUI app of an application is what interfaces with the cli of a program, not the other way around far as I know

I don't really have an answer for you on that one.  We will likely implement a proper CLI that does not require the GUI at some point, I just don't have a time frame available to report.  As noted in our contributing guide, the more thumbs up an issue gets the easier it will be to get that feature on the roadmap.

**Comment by pcbcid** [comment]
> > If you need a user-story internally to get this prioritised - this feels like a regression from my standpoint. I can connect using OpenVPN, but, it used to be a convenient option to just login with windscribe-cli, and, was a differentiating reason for me sticking with Windscribe.
> > As for a temp fix - is there an option to grab the previous version of `windscribe-cli`? Thanks :)
> 
> Yes, you can download the previous Linux CLI app here: https://assets.staticnetcontent.com/desktop/linux/windscribe-cli_1.4-51_amd64.deb

I would like to install windscribe-cli_1.4 in a raspberry pi 4. Do you know if there is an arm64.deb package for this version?

**Comment by bernerdad** [comment]
> I would like to install windscribe-cli_1.4 in a raspberry pi 4. Do you know if there is an arm64.deb package for this version?

Hi.  Sorry, an arm64 build of the old CLI app is not available.

**Comment by xiota** [comment]
> Sorry, an arm64 build of the old CLI app is not available.

If the source is still accessible to developers, could it be published, like in an orphan branch?  Based on the declared license, that seems to be the original intent.

**Comment by bernerdad** [comment]
> > Sorry, an arm64 build of the old CLI app is not available.
> 
> If the source is still accessible to developers, could it be published, like in an orphan branch? Based on the declared license, that seems to be the original intent.

Apologies, I've been told the source is not available.

**Comment by bmn001** [comment]
Seconding the vote for a separate cli client.  Or at least a unified client that doesn't need a desktop environment to run from the command line.

Right now there is no official Windscribe client that works with headless arm64 devices.  There's a lot of Raspberry Pis out there, and they've been increasingly 64 bit (since February 2022!)

I've just been using Wireguard for the last few years and it's fine.  But you guys put a lot of work into your own client and I'd of course prefer to use that.

**Comment by e-t-l** [comment]
> > If you need a user-story internally to get this prioritised - this feels like a regression from my standpoint. I can connect using OpenVPN, but, it used to be a convenient option to just login with windscribe-cli, and, was a differentiating reason for me sticking with Windscribe.
> > As for a temp fix - is there an option to grab the previous version of `windscribe-cli`? Thanks :)
> 
> Yes, you can download the previous Linux CLI app here: https://assets.staticnetcontent.com/desktop/linux/windscribe-cli_1.4-51_amd64.deb

Is there an old standalone version of the CLI for Windows? 

(I've been trying to figure out the best way to connect the VPN on startup but *before* user logon. Right now my best option looks like using the official WG client, run it as a service, and grab a wg config file off the WS website. Unfortunately the site only offers configs for a handful of servers, and my favorites aren't on the list. So, I'm back to looking at seeing if I can start WS as a service from the CLI (to make it a scheduled task). It *seems* like users should be able to run "C:\Program Files\Windscribe\wireguardservice.exe" with a wg .conf file, but that's throwing an error at me so maybe it's just not possible..)

Anyway, a Windows CLI app would be super, if it exists!

**Comment by bernerdad** [comment]
> Is there an old standalone version of the CLI for Windows?

Unfortunately no, the standalone CLI app was Linux only.

**Comment by boludoz** [comment]
No GUI instance detected, starting one now...
GUI is not logged in. Waiting for the login...
Aborting: GUI did not login in time

**Comment by GermanAizek** [comment]
It is a strange decision to prohibit running cli without graphics, there are a lot embedded devices where not have display and vpn access is needed.

**Comment by raycekar** [comment]
Since this is the most thumbed up issue on this repo, by chance has this been discussed to be worked on?

**Comment by bernerdad** [comment]
> Since this is the most thumbed up issue on this repo, by chance has this been discussed to be worked on?

This topic was discussed in our team meeting today.  We'll investigate and estimate the effort involved to implement this, and depending on said effort slot it into our development schedule accordingly.  We'll report back here when we have an idea of which version this will be implemented in.

**Comment by DrPugsley** [comment]
+1-ing this issue. Was planning on using the windscribe app on a headless server only to find out that it is now impossible with the current version. I understand that maintaining 2 separate programs is more difficult, but I and seemingly a bunch of other users would really appreciate it.

**Comment by bernerdad** [comment]
One of our developers is currently implementing this.  We'll hopefully have a guinea pig build for you all to try by end of the month.

**Comment by bernerdad** [comment]
The initial release of the Linux CLI app is available on the Releases page (v2.11.5).  Please open new issues if you find any problems with it, or would like to suggest/request additional features.  Cheers!

**Comment by boludoz** [comment]
> The initial release of the Linux CLI app is available on the Releases page [v2.11.5](https://github.com/Windscribe/Desktop-App/releases/tag/v2.11.5). Please open new issues if you find any problems with it, or would like to suggest/request additional features. Cheers!

And for windows what?

**Comment by bernerdad** [comment]
We have not implemented a version for Windows, as all of the requests for a standalone CLI we received were for a Linux version to support headless operation.
