### ISSUE TITLE
.OVPN broken after upgrading to the latest guinea-pig version 2.8.2

### ISSUE THREAD

**Issue by wellloaded** [Windscribe/Desktop-App#118]
My .ovpn worked just fine but after upgrading to my Windows client to 2.8.2 Guinea pig my VPN connection stopped working:

> [251123 14:06:07:959    597.896] [assert]	 Assertion failed! ( C:\Users\ws-user\Downloads\builds\sw6MyeY9\0\ws\client\desktop\client-desktop-public\client\engine\engine\connectionmanager\connectionmanager.cpp : 182 )
> [251123 14:06:07:959    597.896] [connection]	 ConnectionManager::clickDisconnect()
> [251123 14:06:07:959    597.896] [connection]	 ConnectionManager::onConnectionDisconnected(), state_ = 4
> [251123 14:06:07:960    597.896] [basic]	 stunnel stopped
> [251123 14:06:07:960    597.896] [basic]	 wstunnel stopped
> [251123 14:06:07:970    597.907] [ctrld]	 ctrld process error: "Process crashed"
> [251123 14:06:07:971    597.907] [ctrld]	 ctrld stopped
> [251123 14:06:07:971    597.907] [basic]	 on disconnected event
> [251123 14:06:07:973    597.909] [basic]	 === DNS Configuration begin ===
> [251123 14:06:07:987    597.924] [basic]	 Red Hat VirtIO Ethernet Adapter ( "10.10.10.1" )
> [251123 14:06:07:987    597.924] [basic]	 === DNS Configuration end ===
> [251123 14:06:08:089    598.026] [default]	 MeasurementCpuUsage stopped
> [251123 14:06:16:384    606.320] [user]	 Location selected: "03UK UDP PF.ovpn"
> [251123 14:06:16:543    606.480] [default]	 MeasurementCpuUsage started
> [251123 14:06:16:581    606.517] [basic]	 === DNS Configuration begin ===
> [251123 14:06:16:593    606.529] [basic]	 Red Hat VirtIO Ethernet Adapter ( "10.10.10.1" )
> [251123 14:06:16:593    606.529] [basic]	 === DNS Configuration end ===
> [251123 14:06:16:593    606.529] [basic]	 Connecting to "UK UDP PF.ovpn"
> [251123 14:06:16:593    606.530] [connection]	 "Remotes: ukl2-udp-pf.dns2use.com"
> [251123 14:06:16:596    606.533] [connection]	 Default adapter and gateway: "adapter name = Red Hat VirtIO Ethernet Adapter; adapter IP = 10.10.10.109; gateway IP = 10.10.10.1; remote IP = ; dns = (10.10.10.1); ifIndex = 5"
> [251123 14:06:16:608    606.544] [connection]	 Hostname: "ukl2-udp-pf.dns2use.com"  resolved ->  "45.74.7.5; "
> [251123 14:06:16:608    606.544] [connection]	 Connecting to IP: "45.74.7.5"  protocol: "UDP"  port: 53
> [251123 14:06:16:702    606.638] [ctrld]	 ctrld started on  "127.0.0.1:53"
> [251123 14:06:16:702    606.638] [basic]	 Whitelist connecting ip: "45.74.7.5"
> [251123 14:06:16:703    606.640] [connection]	 connectOVPN
> [251123 14:06:17:311    607.248] [connection]	 OpenVPN version: "2.6.7"
> [251123 14:06:17:352    607.289] [connection]	 openvpn process runned:  56071
> [251123 14:06:19:377    609.313] [connection]	 openvpn process finished before connected to openvpn socket
> [251123 14:06:19:377    609.313] [connection]	 answer from openvpn process, answer = "2023-11-25 14:06:17 cd to 'C:/Users/Fefo/Documents' failed: No such file or directory (errno=2)\r\n2023-11-25 14:06:17 Exiting due to fatal error\r\n"
> [251123 14:06:19:377    609.313] [connection]	 try second attempt to run openvpn after pause 2 sec
> [251123 14:06:21:379    611.315] [connection]	 OpenVPN version: "2.6.7"
> [251123 14:06:21:422    611.358] [connection]	 openvpn process runned:  56104
> [251123 14:06:23:454    613.391] [connection]	 openvpn process finished before connected to openvpn socket
> [251123 14:06:23:455    613.391] [connection]	 answer from openvpn process, answer = "2023-11-25 14:06:21 cd to 'C:/Users/Fefo/Documents' failed: No such file or directory (errno=2)\r\n2023-11-25 14:06:21 Exiting due to fatal error\r\n"
> [251123 14:06:23:455    613.392] [connection]	 ConnectionManager::onConnectionError(), state_ = 1 , error = 7

When I try a new .ovpn it doesn't go as far as asking for credentials.

**Comment by bernerdad** [comment]
HI.  We updated OpenVPN from 2.6.1 to 2.6.7 in this release due to some CVEs.  The `openvpn process finished before connected to openvpn socket` line typically indicates the openvpn daemon failed to start.  If you do a `ldd /opt/windscribe/windscribeopenvpn`, does it indicate there are missing dependencies?

**Comment by wellloaded** [comment]
This is on windows

**Comment by wellloaded** [comment]
Sure I understand.
I can confirm this is a Windows 11 VM with Virtio drivers installed (as it runs over proxmox).

**Comment by bernerdad** [comment]
This issue should be resolved with the upgrade to OpenVPN 2.6.8 in our latest guinea pig build:
https://deploy.totallyacdn.com/desktop-apps/2.8.4/Windscribe_2.8.4_guinea_pig.exe
