### ISSUE TITLE
Repository for RPM and DEB packages

### ISSUE THREAD

**Issue by trytomakeyouprivate** [Windscribe/Desktop-App#121]
similar to Mullvad, for automatic updates and easy installation you should provide a repository that hosts your files.

It should have gpg enabled and a key should either be fetched online like with mullvad, or installed manually like with brave.

https://mullvad.net/de/help/install-mullvad-app-linux

**Comment by yegors** [comment]
Windscribe apps have a self-update mechanism in the GUI, as this is a GUI app. 

Having a repo and configuring it on the client to be used is a lot more work than just downloading and installing an rpm package, and let Windscribe manage the updates after that.

Repos are good for CLI apps and headless devices, which is not applicable for Windscribe.

**Comment by trytomakeyouprivate** [comment]
Does the app use dnf, or zypper, or transactional-update or rpm-ostree? Does it automatically detect what to use?

**Comment by bernerdad** [comment]
Closing this one as a 'will not implement'.  Sorry, we haven't tried the app on Vanilla OS.  We only have enough developer/QA bandwidth to test on the major distros.

**Comment by trytomakeyouprivate** [comment]
Hey, I dont know where you got the VanillaOS from, I specifically mentioned which Distros this will apply to.

This is not a big change. Having a repo is BASIC on every Linux Distro, Apps dont autoupdate this is simply not how its done.

To add more explanations, as you probably havent researched them:
- rpm-ostree: Fedora Atomic Desktops (Silverblue and all others), Ublue.it, Secureblue, Fedora CoreOS, possibly future RHEL versions too
- transactional update: opensuse microOS (kalpa, aeon, ...) which is similar to Fedora image based OSses. This will be the preferred model of Opensuse, with deprecation of Leap entirely. 
- VanillaOS
- [all other Distros mentioned here](https://itsfoss.com/immutable-linux-distros/)

This is not about supporting some weird Distros, this is basic functionality.

As I said on rpm-ostree (only platform I know) this simply does not work. If you add a local App it is different from a repo version.

And this is a good solution on every other Distro too.

This is not Windows. We have package managers and update systems. Please just follow the normal way Linux apps are distributed. 

The advantage is having metadata, versions, and transparency. Immutable Distros are just the extreme, where random unmanaged Updates dont work at all.

On rpm-ostree and all other package managers you can see when an app updates. You can remove it and add it back, you can roll back and pin a version if it fails to work. This is managed versioning and its critical. I have no idea if you have some good system of rolling back a broken update.

I am not even using your VPN to be honest. This is just a requirement for a good app to work as it should on any Linux Distro. You already only support RPM and DEB which is fine, but then please host repos for them. Look at how MullvadVPN did that for reference.

An alternative would be to have it not in a system location at all, as a statically linked binary. This can autoupdate on every distro, for now. But Linux is extremely security flawed in that you can execute files from anywhere, so in the future it should occur that /home or /var/home are mounted non-executable entirely.

So native packages (or flatpak) are the way to go.

Have a nice day!
