### ISSUE TITLE
A blur box around the Linux app

### ISSUE THREAD

**Issue by KarkanAlzwayed** [Windscribe/Desktop-App#122]
I have installed the .tar.zst v2.7.14 on EndeavourOS Linux, and it works without any issues. I only have this weird blurred boxed around the app for some reason. Not sure why it is there. Is it because of the 4k monitor I have? Not sure. I also can only drag the app from that box. Here is a screenshot. 
Thanks 
![windscribe](https://github.com/Windscribe/Desktop-App/assets/49320606/8da8d270-b22d-4343-a7d3-f33bbb22f708)

System:
Operating System: EndeavourOS 
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.112.0
Qt Version: 5.15.11
Kernel Version: 6.6.3-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: A520I AC

**Comment by bernerdad** [comment]
Please try v2.8.4, available in the Releases section.  2.8 updates Qt from 6.3.1 to 6.5.1, which seems to have helped with many visual issues on Linux, especially when using wayland.  Cheers!

**Comment by Ivantheallknowing** [comment]
Could you please try the new 2.9.3 guinea pig build for [Arch Linux](https://deploy.totallyacdn.com/desktop-apps/2.9.3/windscribe_2.9.3_guinea_pig_x86_64.pkg.tar.zst). We've removed the app shadow that might be causing this issue. Thanks!

**Comment by KarkanAlzwayed** [comment]
> Could you please try the new 2.9.3 guinea pig build for [Arch Linux](https://deploy.totallyacdn.com/desktop-apps/2.9.3/windscribe_2.9.3_guinea_pig_x86_64.pkg.tar.zst). We've removed the app shadow that might be causing this issue. Thanks!

Yup, that did it. Thank you so much
