### ISSUE TITLE
How to help translation?

### ISSUE THREAD

**Issue by raspin0** [Windscribe/Desktop-App#125]
Hello, how can I help with translation?

**Comment by bernerdad** [comment]
Hi.  Which languages are you able to help with?

**Comment by raspin0** [comment]
I'm Polish native. From what I could tell the current translation has been auto translated, so I thought I might improve it a little. I'm already a translator for Element and Deepin Desktop.

**Comment by bernerdad** [comment]
Most of the current translations are indeed machine generated.  If you're willing to improve the Polish translation, that would be very most appreciated!  You can make the improvements in the following files and submit them as  a PR:
- client/gui/translations/ws_desktop_pl.ts
- installer/common/translations/windscribe_installer_pl.ts
- installer/windows/uninstaller/translations/windscribe_uninstaller_pl.rc

**Comment by raspin0** [comment]
So I have finished translating, but is there a way to try out translation without recompiling?

**Comment by bernerdad** [comment]
Thanks!  The only way to see how the revised translations look in the UI is to recompile.

**Comment by raspin0** [comment]
I have complied the app in WSL on Ubuntu 22.04 and encountered an issue with missing qwayland library and it turned out that readme instruction for linux is missing `libwayland-dev` in dependencies.

**Comment by bernerdad** [comment]
Thanks again for your efforts on this!  Please add the missing dependency to the README and submit it as part of your PR.  Cheers!

**Comment by bernerdad** [comment]
Would you be willing to provide updated translations for our Android and iOS apps on CrowdIn?  If yes, I'll get you in touch with our translations coordinator to set things up.  Thanks again, and have an excellent weekend!

**Comment by bernerdad** [comment]
@raspin0 Were all your changes overridden,  or only some of them?

**Comment by raspin0** [comment]
@bernerdad Everything was overridden

**Comment by bernerdad** [comment]
That is very odd.  We did integrate your improvements into our internal repo, so they should be reflected here.  We'll investigate and rectify the situation as soon as we have a bit of free bandwidth.

**Comment by bernerdad** [comment]
Very glad we didn't wipe out all your hard work!  We'll circle around to this when time permits and repair any entries not impacted by a source string change.

**Comment by bernerdad** [comment]
@raspin0 This should be resolved now.  Fixed translations will land in the 2.11.5 release.  Thanks again for providing this translation help.
