### ISSUE TITLE
Pressing 'No' in 'ignore SSL errors' prompt shouldn't log out user

### ISSUE THREAD

**Issue by ltguillaume** [Windscribe/Desktop-App#130]
Currently, the 'ignore SSL errors' prompt is triggered rather happily (e.g. it's often shown if there is no autoconnect to a wireless network upon boot, while Windscribe _is_ automatically started at boot).

To make things even worse, the 'ignore SSL errors' prompt locks up the Windscribe window for a while, and after pressing 'No', it completely logs out the user.

Using v2.9.2 and v2.9.4 on latest Windows 11 Pro
No 3rd party firewall, no 3rd party anti-malware

I missed the log entries (they were already overwritten, even the previous logs... Perhaps it's a good idea to implement more log retention?) As soon as it happens again, I'll see if there are relevant log entries.

**Comment by bernerdad** [comment]
Thank you for reporting this.  It will be fixed in v2.9.5.  Cheers!
