### ISSUE TITLE
Windscribe not working reliably with NetworkManager/KDE

### ISSUE THREAD

**Issue by Nuc1eoN** [Windscribe/Desktop-App#135]
My experience with Windscribe and NetworkManager (on kde) is not so good. Windscribe gui often complains that "something is interfering" with it's network (I am always sending the debug log to your team). Often it will not work correctly. Sometimes I will be unable to access local networks unless I enable Windscribe (like access to my printer). After coming back from suspend/sleep state it is also not working correctly. I have to restart the NetworkManager or windscrbe-helper services.

I am on ArchLinux with NetworkManager on KDE. My current setup is that windscribe auto-connects on login.

I can provide more information or logs if there is a need. It is hard to exactly pinpoint the problems as they seem "random" or hard to debug.

**Comment by bernerdad** [comment]
Hi.  Please upgrade to 2.9.9, if you haven't already, and provide us with a log from that version.  One of us devs will look into the issue.  Some things to try that may help narrow down the problem:
- Does the issue occur on all protocols?  E.g. if you are using WireGuard, try using UDP and see if the issue still occurs.
- If you are using any of the more advanced options (split tunneling, custom DNS, etc.), try turning them off and see if the issue still occurs.  If it does not, start turning the advanced options back on one-by-one until you find which one is causing the issue.
