### ISSUE TITLE
Slow connection at first launch after upgrading

### ISSUE THREAD

**Issue by sith-on-mars** [Windscribe/Desktop-App#138]
OS: OpenSUSE Aeon
Windscribe version: 2.10.2

The first time connection took quite long time (2 to 3 mins I think). If I reconnected to internet after the first time connection, the connection speed became normal again. @bernado82 pointed out that upgrading Windscribe without rebooting the system or uninstalling the previous version was the culprit. Please see their quote below:

> I think it happens because Windscribe has been updated OVER a running version. There is no **_killall_** or **_pkill_** command in installation script for the Windscribe process and **windscribe-helper** service isn't stopped either. To avoid a slow connection at first launch, reboot the system or uninstall the previous version before updating (uninstall script kill or disable Windscribe process and service).

**Comment by jaxu** [comment]
The official RPMs (intended for Fedora) do actually manage the underlying windscribe-helper on install/uninstall via RPM scriptlets, and using the in-app update does call a script which handles killing the running WIndscribe process as well.

If you are using the repackaged RPM from bernardo82, it's possible that it's missing the scriptlets.  As we don't have official support for OpenSUSE at this time, this will be unlikely to be resolved.  Please use the workaround as described for now.

**Comment by sith-on-mars** [comment]
Thanks! I'm using the official package not the repacked RPM from @bernardo82.

**Comment by bernerdad** [comment]
Hi.  Can you let us know if this is still an issue with the latest guinea pig [build](https://github.com/Windscribe/Desktop-App/releases/tag/v2.11.6)?  There is an OpenSUSE-specific installer available there now.  Thanks!

**Comment by bernado82** [comment]
Last v2.11.**6** (alpha) fix annoying _"logout after each reboot"_ bug, encountered with previous build. In app auto-update works well with openSUSE also. Thanks! This last (alpha) build can be released now.

**Comment by bernado82** [comment]
Last v2.11.6 (alpha) fix annoying "logout after each reboot" bug,
encountered with the previous build. In app auto-update works well with
openSUSE also. Thanks!

Le ven. 9 août 2024 à 23:54, Jonathan Martin ***@***.***> a
écrit :
