### ISSUE TITLE
Builds for alpine linux

### ISSUE THREAD

**Issue by vixalien** [Windscribe/Desktop-App#139]
Hello. I like Windscribe, but I can't use it on Alpine Linux because the builds provided all use glibc, but Alpine uses musl libc. Any plans to provide a libc build?

**Comment by bernerdad** [comment]
Hi.  Sorry, we have no plans to support this distro in the immediate future.

**Comment by vixalien** [comment]
That's okay.

If I may ask, is the build process for the executables open source, so I can see if I can make a custom executable?

**Comment by bernerdad** [comment]
Yes it is.  Take a look at the Linux section in the README for instructions on how to build the app from source.  Cheers!
