### ISSUE TITLE
rpm for rhel 8.x

### ISSUE THREAD

**Issue by bobOnGitHub** [Windscribe/Desktop-App#141]
There's only one desktop Fedora/Centos rpm download on the web site.

I tried it on Alma Linux 8.9 ( clone of Latest RHEL 8.x which will be stopping LTS for 5 yrs on 8.10 in the next few months )

```
/opt/windscribe/Windscribe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/windscribe/Windscribe)
/opt/windscribe/Windscribe: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /opt/windscribe/lib/libQt6Widgets.so.6)
/opt/windscribe/Windscribe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/windscribe/lib/libQt6Widgets.so.6)
/opt/windscribe/Windscribe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /opt/windscribe/lib/libQt6Widgets.so.6)
/opt/windscribe/Windscribe: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /opt/windscribe/lib/libQt6Gui.so.6)
/opt/windscribe/Windscribe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/windscribe/lib/libQt6Gui.so.6)
/opt/windscribe/Windscribe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /opt/windscribe/lib/libQt6Gui.so.6)
/opt/windscribe/Windscribe: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /opt/windscribe/lib/libQt6Core.so.6)
/opt/windscribe/Windscribe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.28' not found (required by /opt/windscribe/lib/libQt6Core.so.6)
/opt/windscribe/Windscribe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/windscribe/lib/libQt6Core.so.6)

```

**Comment by bernerdad** [comment]
Hi.  We build the rpm on Fedora 32, and use the pre-built Qt 6.5 binaries, which require a minimum of RHEL 8.8.  You could try building the app and libraries from source on your distro to get a working version.

**Comment by bobOnGitHub** [comment]
@bernerdad,

I'm on Alma Linux 8.9 which is a RHEL 8.9 clone.
I dunno what the case is with Fedora 32 but on a bang up-to-date AL 8.9

```
]$ strings /usr/lib/libstdc++.so.6 | grep LIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_DEBUG_MESSAGE_LENGTH
GA+GLIBCXX_ASSERTIONS
GA+GLIBCXX_ASSERTIONS
```

**Comment by bernado82** [comment]
Have you tried other Winscribe builds?

For example, from https://windscribe.com/changelog/linux_rpm  you could download the following (older) versions:

v**2.6.14** (stable)
https://deploy.totallyacdn.com/desktop-apps/2.6.14/windscribe_2.6.14_x86_64.rpm
v**2.7.14** (stable)
https://deploy.totallyacdn.com/desktop-apps/2.7.14/windscribe_2.7.14_x86_64.rpm

It's possible that this may be installable on your system.. Give it a try and confirm, or deny.

**Comment by bernerdad** [comment]
We originally tried to use RHEL 8, and derivative, Docker images for our CI, and ran into all sorts of headaches.  Since Fedora is on our officially supported distros list, we opted to use Fedora in CI.  Perhaps yourself or another community member can tackle seeing if the app will build on AL?  I'm going to close this as there is nothing we can action here.
