### ISSUE TITLE
VPN traffic and captcha

### ISSUE THREAD

**Issue by wellloaded** [Windscribe/Desktop-App#143]
Many popular websites like google.com to mention one have some sort of DDOS protection that requires users to pass a very annoying captcha. I guess this is happening because the outbound WS IPs are limited in number and a given IP will generate a large number of queries from many different WS users.

Can you think of a good way to avoid this issue and have the user browsing Internet without such interruptions? Perhaps increasing the public IP pools or something?

Thanks

**Comment by bernerdad** [comment]
Please let our support team know when you encounter a captcha, with details on which VPN location you were connected to and which site(s) are generating a captcha.  They'll coordinate a resolution.  Thanks!

**Comment by wellloaded** [comment]
I get plenty of captcha when connected to Johannesburg (South Africa)
I can mention google right here right now (just re-tested and it still happens) but I'm 100% certain there were many more sites. I just didn't note them down.

HTH
