### ISSUE TITLE
Why you add a limit of 50 IP to the split tunneling section?

### ISSUE THREAD

**Issue by unrated1** [Windscribe/Desktop-App#145]
I added the entire IP range of Iran to this section, and it was working for me without any problems, without hangs, and without bugs, until I realized that in the new version, you added a limit of 50 IPs to this section. Why?

![oeJjnes6YcCw1FaEKwO2KBB2ZJJo6BWXJ8hE1Z63gzedhop9Dzn6IX3k6ravTgHy-asdasdasd](https://github.com/Windscribe/Desktop-App/assets/13558344/8c06ab4e-d3f3-4b25-88d4-d6e25fe827d1)

**Comment by bernerdad** [comment]
Hi.  We're looking into changing this to only apply the limit to hostnames.  We'll report back here when and if a build is available with this change.

**Comment by bernerdad** [comment]
We're going to close this one as 'resolved'.  Please reopen if you find otherwise.  Cheers!
