### ISSUE TITLE
Issues with status tray icon on Xubuntu

### ISSUE THREAD

**Issue by amirrh6** [Windscribe/Desktop-App#147]
Hey folks, thank you for your awesome software.

I recently switched to Xubuntu 23.10 and installed Windscribe v2.9.9. The connection seems to be working fine, however the status tray icon is not working as expected:

1- Clicking on status tray icon does not do anything: (Whether Windscribe is minimized to tray or not)

https://github.com/Windscribe/Desktop-App/assets/65363030/03e1e3e3-a858-47d5-9e13-18361b1154e9

2- XFCE's 'windows button' panel plugin doesn't seem to recognize Windscribe icon:

![image](https://github.com/Windscribe/Desktop-App/assets/65363030/e871fd1d-dfac-4b96-8e0e-12da9afca4eb)

Let me know if you needed any more info for better debugging.

**Comment by jaxu** [comment]
Thanks for the report!

For the tray icon, we already have this on our board and will fix it in a future build.

For XFCE's window panels, for some reason it does not recognize the icon if it has a different name than the application.  Will add this to our tasks.  Thanks.

**Comment by bernerdad** [comment]
Hi.  This should be fixed in our latest [build](https://github.com/Windscribe/Desktop-App/releases/tag/v2.11.5).  Please give it a whirl if you can and let us know if it is indeed resolved for you.  Thanks!

**Comment by amirrh6** [comment]
I can confirm that both of the reported issues are resolved.
Big respect!
Feel free to close the issue.

**Comment by bernerdad** [comment]
Thank you for confirming the fix for us!
