### ISSUE TITLE
Ubuntu 24.04

### ISSUE THREAD

**Issue by Artaherzadeh** [Windscribe/Desktop-App#148]
Can't install deb file due to no app installer in Ubuntu and using command, we get error or the app malfuntion

**Comment by bernerdad** [comment]
Hi.  We're unable to reproduce this issue.  Can you provide more detail, and perhaps submit a debug log to our support team?

**Comment by bernerdad** [comment]
It looks like this may be an issue (feature?) with Ubuntu itself: https://news.slashdot.org/story/24/05/04/202207/ubuntu-criticized-for-bug-blocking-installation-of-deb-packages
