### ISSUE TITLE
What does "circumvent censorship" exactly do?

### ISSUE THREAD

**Issue by amirrh6** [Windscribe/Desktop-App#149]
Hey, I just wanted to know how this features changes the behavior of Windscribe.

Why isn't it always enabled? In other words, why it has to be manually enabled? Does it introduce any downsides if enabled  without real necessity?

I've seen some strange behavior when it is enabled like sometimes Windscribe circumvents censorship better when it disabled!

Thank you!

**Comment by bernerdad** [comment]
Hi.  The feature is automatically enabled for new users, or if an existing user does a factory reset during manual install, and the app detects your OS default language is set to Belarusian, Farsi, Russian, Turkish, or Chinese.  Typically one would only enable this feature if they are in that list and are unable to connect, with any protocol, with the feature disabled.  Enabling the feature enables additional logic in the VPN protocols (except IKEv2) that attempts to bypass restrictions on adversarial networks.

**Comment by GeniusBroccoli** [comment]
> Hi. The feature is automatically enabled for new users, or if an existing user does a factory reset during manual install, and the app detects your OS default language is set to Belarusian, Farsi, Russian, Turkish, or Chinese. Typically one would only enable this feature if they are in that list and are unable to connect, with any protocol, with the feature disabled. Enabling the feature enables additional logic in the VPN protocols (except IKEv2) that attempts to bypass restrictions on adversarial networks.

Can you explain a little more this additional logic?

**Comment by bernerdad** [comment]
https://windscribe.com/features/circumvent-censorship/ has all the info we can publicly share on this feature.  The special sauce of it must remain 'eyes only'.

**Comment by GeniusBroccoli** [comment]
> https://windscribe.com/features/circumvent-censorship/ has all the info we can publicly share on this feature. The special sauce of it must remain 'eyes only'.

I'm understand. Okay, can you say, does it use anti DPI or not?

**Comment by safehouse7430** [comment]
"How does it work?
If we told you, we would have to kill you."
I don't understand why. Isn't the idea behind opensource software that if it can indeed guide attackers towards successfully finding vulnerabilities, it also helps people/companies/groups contribute to the software ?
And aren't other censorship circumvention tools, like Psiphon, Mullvad, AmneziaWG, IVPN, …, fully open source? How is it a problem for you and not for them to reveal the secret sauce ? It was something I was wondering for a long time.
