### ISSUE TITLE
Fix minimize bug on ubuntu

### ISSUE THREAD

**Issue by par3ae** [Windscribe/Desktop-App#15]
Hi dear windscribe developers
thanks for new gui app for linux

this app has a bug and that is that we can't minimize this app to system tray.
it should always be open and when we want to just close the app, it ask us if we want to close windscribe and then it completely quit and stopped the app.
 we have a similar "start minimized" section in settings but I don't know what is it!

It was great if when we click on close arrow in the app, it just minimized the app to tray and if we want to quit the app we do it by right click on tray icon and press "Exit"

best regards

**Comment by KITKATKILLER67** [comment]
Start minimized mean it starts in the tray. (Windows)
I'm on Windows so it might not be the same thing for Linux users.

**Comment by bernerdad** [comment]
We've added the 'Minimize and close to tray' feature for Linux to our to-do board. Cheers!

**Comment by par3ae** [comment]
> We've added the 'Minimize and close to tray' feature for Linux to our to-do board. Cheers!

Excuse me dear Jonathan
Is there an estimate time to release new version which 'Minimize and close to tray' feature added?

**Comment by bernerdad** [comment]
Hi.  I'm going to estimate mid- to late April at the earliest for this one.

**Comment by ryleu** [comment]
I think this should be renamed to "Window doesn't minimize to tray on Linux" to more accurately describe the issue. It works the same way on every platform I've tested: GNOME, KDE, and Cinnamon.

**Comment by par3ae** [comment]
> Hi. I'm going to estimate mid- to late April at the earliest for this one.

Hi again dear Jonathan
I hope you are fine
We are still waiting for this update.
Does it come until the end of April? :)

**Comment by bernerdad** [comment]
Hi.  We're just putting the finishing touches on the 2.4 release.  This issue will be worked on for the 2.5 release, so likely sometime in mid to late May before a build is available with this feature added.

**Comment by par3ae** [comment]
> Hi. We're just putting the finishing touches on the 2.4 release. This issue will be worked on for the 2.5 release, so likely sometime in mid to late May before a build is available with this feature added.

Oh, really?
I think it would be fixed in 2.4 release :(
So we should wait more than 1 month for this fix in release 2.5 
I hope you release 2.5 sooner :+1:

**Comment by bernerdad** [comment]
Please have a look at:
https://github.com/Windscribe/Desktop-App/issues/18#issuecomment-1113578762

**Comment by bernerdad** [comment]
Hi.  v2.5.6 is available in our guinea pig channel, and it resolves this issue.  Cheers!

**Comment by candroid-man** [comment]
Not able to minimize to tray on Fedora

**Comment by bernerdad** [comment]
@candroid-man We are unable to reproduce this on Fedora 40 and app version 2.11.5.  What is the exact version and flavor of Fedora you are using, and Windscribe app version?

**Comment by candroid-man** [comment]
Windscribe version 2.10.15, and Fedora 40 Workstation

![image](https://github.com/user-attachments/assets/a40e3921-0604-4ca9-a459-0d7595d724d0)

![image](https://github.com/user-attachments/assets/0d38b0ac-6e20-42d5-a2ff-9cb74e3c0f79)

**Comment by jaxu** [comment]
Fedora doesn't ship with a 'tray', you'll need to install one such as from here: https://extensions.gnome.org/extension/615/appindicator-support/ before the option shows up.

**Comment by candroid-man** [comment]
So you have to have a system tray to close the app? Other VPN apps can close and still run just fine such as IVPN and ProtonVPN, even Mullvad. It just tells you before you close something like "this app will not close, it is going to run in the background". Is something like that possible with Windscribe?

**Comment by jaxu** [comment]
No, you need a tray to minimize/close to tray.  Although this is an approximation of running in the background, this is very much not the same thing, and such a mode does not currently exist in the app.

**Comment by candroid-man** [comment]
I have submitted a new issue that would fix this, and upgrade the CLI utility as well: https://github.com/Windscribe/Desktop-App/issues/163
