### ISSUE TITLE
Disconnect from macOS desktop client is unreliable and extremely slow

### ISSUE THREAD

**Issue by d7an** [Windscribe/Desktop-App#153]
Winscribe: 2.10.12 (Beta)
macOS: Sonoma 14.5

Clicking on Disconnect from menu/icon sometime seems unresponsive/unreliable and many time appeared hang, and I've to resort to killing the "windscribe*" related system processes from Activity app. It usually happens after using Windscribe for awhile. Choosing disconnect immediately after connecting typically works without problem.

Is there anything from the ~/Library/Application Support/Windscribe/Windscribe2/log_gui.txt that can be helpful for you?

**Comment by bernerdad** [comment]
Hi, and thank you for notifying us of this issue.  The next time it occurs, please send us that log_gui.txt log file and also the helper log located in `/Library/Logs/com.windscribe.helper.macos/helper_log.txt`.  That will aid us in tracking down the component causing the issue.

**Comment by d7an** [comment]
> Hi, and thank you for notifying us of this issue. The next time it occurs, please send us that log_gui.txt log file and also the helper log located in `/Library/Logs/com.windscribe.helper.macos/helper_log.txt`. That will aid us in tracking down the component causing the issue.

Can I click the "Send debug log" from within the app?

The other issue is, choosing to quit the app sometime also takes forever, you'll see a spinning circle going on and on...
![Windscibe Mac-quite](https://github.com/Windscribe/Desktop-App/assets/1724924/90726f57-7985-41de-a112-c1b7b991bf32)

**Comment by bernerdad** [comment]
Yes, that will work.  When you do so, please DM me your Windscribe username so I can then find the logs in our support system.  Cheers!

**Comment by huangyy126** [comment]
The experience of using this software in China shows that it can be used from October 1, 2023 to April 10, 2024. However, from April 11, 2024 to now, it is basically unable to connect to any nodes. I have tried the latest version and the problem remains the same as before

**Comment by bernerdad** [comment]
@huangyy126 Did you enable the anti-censorship feature in preferences and try every protocol?

**Comment by huangyy126** [comment]
From October 1, 2023 to October 10, 2024, software can basically connect to nodes using the UDP protocol. Starting from April 10, 2024, I have tried to enable anti censorship function in the settings and tried each protocol, but the computer cannot connect to any nodes, and the Android version can hardly connect to any nodes (only 2-3 times successfully connected using the Stealth protocol), which may be related to the special environment in China. I have tried other VPNs, such as OpenVPN, Wireguard, Shadow, UDP, ZoogTLS, etc., and have successfully connected to them. Now let's give feedback on the situation. Similar to the situation - a few days ago, the official banned most of the IP4 that Warp can use, resulting in Warp being basically unable to connect.

**Comment by bernerdad** [comment]
@huangyy126 Please try our latest beta release (2.10.14) and let us know if it allows you to connect.  Also, please start a new GitHub issue to track this so we do not pollute this one with unrelated information.  Thanks!

**Comment by bernerdad** [comment]
@d7an Do you have a fair number of split tunnel hostnames configured?  If yes, please export your settings as a backup, remove the hostnames, and let us know if that resolves the issue.  Thanks!

**Comment by bernerdad** [comment]
@d7an Please try the new 2.11.4 release and let us know if it resolves the issue for you.  Thanks!

**Comment by d7an** [comment]
> > Hi, and thank you for notifying us of this issue. The next time it occurs, please send us that log_gui.txt log file and also the helper log located in `/Library/Logs/com.windscribe.helper.macos/helper_log.txt`. That will aid us in tracking down the component causing the issue.
> 
> Can I click the "Send debug log" from within the app?
> 
> The other issue is, choosing to quit the app sometime also takes forever, you'll see a spinning circle going on and on... ![Windscibe Mac-quite](https://private-user-images.githubusercontent.com/1724924/342019782-90726f57-7985-41de-a112-c1b7b991bf32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1Mjg2MzAsIm5iZiI6MTcyMDUyODMzMCwicGF0aCI6Ii8xNzI0OTI0LzM0MjAxOTc4Mi05MDcyNmY1Ny03OTg1LTQxZGUtYTExMi1jMWI3Yjk5MWJmMzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDlUMTIzMjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDJjYmIyNTRhZTZmZDFjMDU4ZGE4ZWE4MjYyOWI5YzIwZWM1OTAzNDU4ZjdlNzU4MTM5NDgzYmZmOGE5MTM4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SYNYT2VBhg3q_PGAeLRevUvF2wxMQF1khHeDTCtq1O0)

@bernerdad Even at 2.11.4Alpha, quitting from Windscribe still might encounter this spinning arrow problem. Usually after using Windscribe for a while. Launching and Quicking Windscribe immediately has no such problem.

**Comment by bernerdad** [comment]
@d7an We've made further improvements in this area with this [release](https://github.com/Windscribe/Desktop-App/releases/tag/v2.11.7).  Please let us know if it resolves the issue for you.  Cheers!
