### ISSUE TITLE
Fedora Workstation 40 upgrade to 2.10.15 no longer connects with custom DNS enabled.

### ISSUE THREAD

**Issue by GrapeBacon** [Windscribe/Desktop-App#157]
About a week ago I posted on your sub-reddit about an issue with Fedora 40 on a clean install where I would try and use a custom DNS (ControlD DoH profile) and the VPN would connect but DNS resolution would not happen. A staff member, I believe, said to switch the DNS Manager from Auto to systemd-resolved. This worked.

Today I updated to GUI app version 2.10.15 and I am no longer able to connect. The message is "Unable to start custom DNS service. Please ensure you don't have any other local DNS services running, or contact support."

Since this is a stock Fedora 40 install with only Windscribe installed at this time, I don't have any other custom DNS resolvers installed.

I have restarted the machine after the upgrade with the same results.

Related settings: 
* Connected DNS -> Custom -> Upstream 1 -> DoT resolver (also tried DoH) for ControlD "<id>.dns.controld.com"
* App Internal DNS -> ControlD
* DNS Manager -> systemd-resolved (also tried NetworkManager and Auto).

``` uname -a
Linux fedora 6.9.6-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun 21 15:48:21 UTC 2024 x86_64 GNU/Linux
```
Thank you.

**Comment by bernerdad** [comment]
Right after seeing this message, please send us a debug log using the `Send Debug Log` feature in `Help`.  Once you've sent the log, DM me your Windscribe username so that I can locate it in our support system.  Once we have the log, I suggest rolling back to the previous working version of the app to restore your custom DNS functionality while we diagnose the issue.  Thanks!

**Comment by Ivantheallknowing** [comment]
@GrapeBacon I've been able to reproduce the issue. Could you please try reloading the helper in your terminal? Run this command `sudo systemctl restart windscribe-helper`. Then try to connect again, it should work this time.

**Comment by GrapeBacon** [comment]
Logs were sent. 

```
 sudo systemctl restart windscribe-helper
```

Did not resolve the issue for me.

**Comment by GrapeBacon** [comment]
Closing as I've moved on.
