### ISSUE TITLE
WireGuard connection fails or is slow to connect with DoH

### ISSUE THREAD

**Issue by laserjobs** [Windscribe/Desktop-App#160]
WireGuard does not connect or is very slow to connect with the DNS is set to a DoH provider

1. Connection -> Connected DNS -> Custom
2. Set to https://dns.cloudflare.com/dns-query
3. Try to connect with WireGuard

**Comment by bernerdad** [comment]
Please try the [2.11.5](https://github.com/Windscribe/Desktop-App/releases/tag/v2.11.5) release and let us know if it resolves this issue.  Thanks!

**Comment by laserjobs** [comment]
It did not resolve the issue and it is one of those crappy bugs where sometimes it does connect really fast other times it takes awhile and sometimes it doesn't connect. This is only when using DoH and I am seeing the same behavior switching the connection between UDP and WireGuard. Hope this helps

**Comment by bernerdad** [comment]
Thanks for trying that build out.  We'd hoped 2.11.5 would resolve this as we've fixed a specific custom DNS issue in it that sounds like this one.  If you run into another instance of the connection taking a long time, or failing to connect, please send us a debug log before exiting the app.  You'll find the 'Send Debug Log' feature in the Help section of preferences.  You'll also have to send us your Windscribe username, as it is the only way for us to find a debug log in our system. You can email it to me if you like (jonathan_at_windscribe_dot_com).  Cheers!

**Comment by laserjobs** [comment]
I did send one today when the app got a connection error. Same username.

**Comment by bernerdad** [comment]
I've retrieved the log and created an internal ticket.  One of us devs will look at it asap.  One other question, did this work fine for you in the previous stable release (2.9.9)?  Thanks!

**Comment by laserjobs** [comment]
I do not think so.

**Comment by laserjobs** [comment]
Interesting discovery, if I start the app and do nothing it does not connect. If I minimize and maximize or bring the app in and out of focus it connects.

**Comment by bernerdad** [comment]
One of our developers is actively working on this now.  We'll report back here when a guinea pig build is available with this issue fixed.

**Comment by bernerdad** [comment]
This should be fixed in the 2.11.6 guinea pig [build](https://github.com/Windscribe/Desktop-App/releases/tag/v2.11.6).

**Comment by laserjobs** [comment]
That seems to have fixed the issue, Thanks.
