### ISSUE TITLE
Failed to connect to bus: No medium found Could not start application

### ISSUE THREAD

**Issue by Srjackbuckles** [Windscribe/Desktop-App#161]
I have been struggling to find a working version of Windscribe to run on my headless Debian server. I successfully installed windscribe-cli_2.11.5_guinea_pig_amd64.deb, but when running any command `windscribe-cli status` or `windscribe-cli login "myusername" "mypassword" "2FA" ` for example, I get 
`Failed to connect to bus: No medium found` 
`Could not start application`

**Comment by Ivantheallknowing** [comment]
Sounds like you used `dpkg` to install the cli package, which didn't resolve dependencies required. Put attempt to reinstall the package with `apt` instead.

**Comment by Srjackbuckles** [comment]
Unfortunately that did not fix the issue. Here is what I ran
```
root@ms-hcvanilla:/home# sudo apt install ./windscribe-cli_2.11.5_guinea_pig_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'windscribe-cli' instead of './windscribe-cli_2.11.5_guinea_pig_amd64.deb'
The following NEW packages will be installed:
  windscribe-cli
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/19.2 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /home/windscribe-cli_2.11.5_guinea_pig_amd64.deb windscribe-cli amd64 2.11.5 [19.2 MB]
Selecting previously unselected package windscribe-cli.
(Reading database ... 49978 files and directories currently installed.)
Preparing to unpack .../windscribe-cli_2.11.5_guinea_pig_amd64.deb ...
Finish pre-install script
Unpacking windscribe-cli (2.11.5) ...
Setting up windscribe-cli (2.11.5) ...
Created symlink /etc/systemd/system/multi-user.target.wants/windscribe-helper.service -> /etc/systemd/system/windscribe-helper.service.
root@ms-hcvanilla:/home# windscribe-cli status
Failed to connect to bus: No medium found
Could not start application
```

**Comment by jaxu** [comment]
> Unfortunately that did not fix the issue. Here is what I ran
> 
> ```
> root@ms-hcvanilla:/home# sudo apt install ./windscribe-cli_2.11.5_guinea_pig_amd64.deb
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Note, selecting 'windscribe-cli' instead of './windscribe-cli_2.11.5_guinea_pig_amd64.deb'
> The following NEW packages will be installed:
>   windscribe-cli
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 0 B/19.2 MB of archives.
> After this operation, 0 B of additional disk space will be used.
> Get:1 /home/windscribe-cli_2.11.5_guinea_pig_amd64.deb windscribe-cli amd64 2.11.5 [19.2 MB]
> Selecting previously unselected package windscribe-cli.
> (Reading database ... 49978 files and directories currently installed.)
> Preparing to unpack .../windscribe-cli_2.11.5_guinea_pig_amd64.deb ...
> Finish pre-install script
> Unpacking windscribe-cli (2.11.5) ...
> Setting up windscribe-cli (2.11.5) ...
> Created symlink /etc/systemd/system/multi-user.target.wants/windscribe-helper.service -> /etc/systemd/system/windscribe-helper.service.
> root@ms-hcvanilla:/home# windscribe-cli status
> Failed to connect to bus: No medium found
> Could not start application
> ```

windscribe-cli spawns a user service if it's not already running, however you are logged in as root.  Please do not run windscribe-cli as root.

**Comment by Srjackbuckles** [comment]
I created a new user, and reran the command and I am still getting the same error
`server@ms-hcvanilla:~$ windscribe-cli status`
`Failed to connect to bus: No medium found
Could not start application`

**Comment by jaxu** [comment]
I'm unable to replicate on a fresh Debian 12 headless install; as root I get the "No medium found" message, as any other user, the app launches and provides the status.

Have you done anything to DBus on this installation?  What's the value of $DBUS_SESSION_BUS_ADDRESS?

**Comment by Srjackbuckles** [comment]
I am not sure what you are referring to as far as DBus. This is a Debian installation running on a LXC container hosted by Proxmox.

**Comment by jaxu** [comment]
Unfortunately we do not support running the clients in containerized/virtualized environments, since they often run into exactly this kind of problem.

If you are able to reproduce this on real hardware, we are happy to help, or if you are able to debug this yourself and come up with a solution, we'd be happy to have your [contribution](https://github.com/Windscribe/Desktop-App/blob/bca1850babb1d66269a0bd56f74436db22f8530b/CONTRIBUTING.md).

**Comment by Srjackbuckles** [comment]
Okay, I will close this thread then. Are there any other ways for me to be able to forward my virtual servers to my wind-scribe static IP, or do I just need to cancel that service?

**Comment by jaxu** [comment]
If I understand correctly, you want your virtual servers to be reachable at your WS static IP?  Short of switching to dedicated servers, I can't think of a quick solution offhand.  I apologize that we're unable to meet this requirement as it's not a typical scenario -- please feel free to cancel if you aren't able to make use of the service.
