### ISSUE TITLE
AppImage package

### ISSUE THREAD

**Issue by Hikiru** [Windscribe/Desktop-App#162]
I use a Steam Deck with a dock as my primary PC, and SteamOS makes it very hard to install Windscribe and it could be deleted with an update. As I've seen on another issue that Flatpak has hurdles to overcome, consider trying AppImage. I just want a way to run Windscribe on my Steam Deck easily. I tried an openvpn configuration but torrenting doesn't work for some reason.

**Comment by bernerdad** [comment]
It's unlikely we'll be able to implement this, since we install a helper service that needs to run as root.  AppImage, like Flatpak appears to prevent us from doing that.
