### ISSUE TITLE
Lots of PTR requests through the Windows App

### ISSUE THREAD

**Issue by laserjobs** [Windscribe/Desktop-App#166]
Not really sure how to duplicate the issue but it had something to do with changing location when I got a bunch of PTR requests
252.0.0.224.in-addr.arpa
239.20.18.104.in-addr.arpa
42.206.58.216.in-addr.arpa
69.210.218.23.in-addr.arpa
50.4.18.104.in-addr.arpa
99.186.250.142.in-addr.arpa
73.79.16.104.in-addr.arpa
6.121.82.140.in-addr.arpa
184.110.17.104.in-addr.arpa
14.50.239.18.in-addr.arpa
22.112.82.140.in-addr.arpa
86.88.20.104.in-addr.arpa
3.121.82.140.in-addr.arpa
86.89.20.104.in-addr.arpa
40.132.190.20.in-addr.arpa
44.246.107.13.in-addr.arpa
108.244.17.2.in-addr.arpa
84.102.250.142.in-addr.arpa
206.185.250.142.in-addr.arpa
227.185.250.142.in-addr.arpa
251.0.0.224.in-addr.arpa
206.184.250.142.in-addr.arpa
b.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.2.0.f.f.ip6.arpa
193.16.217.172.in-addr.arpa
227.184.250.142.in-addr.arpa
226.185.250.142.in-addr.arpa
22.2.76.76.in-addr.arpa
11.31.92.23.in-addr.arpa
1.80.190.35.in-addr.arpa
132.185.250.142.in-addr.arpa
14.18.217.172.in-addr.arpa
227.67.152.185.in-addr.arpa
239.20.18.104.in-addr.arpa
69.68.204.143.in-addr.arpa
106.186.250.142.in-addr.arpa
184.110.17.104.in-addr.arpa
50.4.18.104.in-addr.arpa
5.74.20.2.in-addr.arpa
73.79.16.104.in-addr.arpa
20.36.159.162.in-addr.arpa
48.22.88.149.in-addr.arpa
5.36.159.162.in-addr.arpa
25.112.82.140.in-addr.arpa
26.114.82.140.in-addr.arpa
35.22.88.149.in-addr.arpa
142.79.18.2.in-addr.arpa
10.129.14.23.in-addr.arpa
148.31.102.82.in-addr.arpa
26.112.82.140.in-addr.arpa
86.88.20.104.in-addr.arpa

**Comment by bernerdad** [comment]
Which app version is producing this, and can you reproduce it with the previous stable build?

**Comment by laserjobs** [comment]
I really am not sure how to reproduce the issue, are those requests related to R.O.B.E.R.T malware blocking by chance?

**Comment by bernerdad** [comment]
We don't believe this is R.O.B.E.R.T related.  Quite a few of these reverse lookup to Google cloud and GitHub services.  Let us know which version of the Windows app you are running and we'll keep an eye out for additional user reports.  Thanks!

**Comment by laserjobs** [comment]
v2.11.6 on WireGuard

**Comment by laserjobs** [comment]
It has something to do with Control-D when blocked by the Windows firewall. It was showing a direct connection to my residential IPv6 so it might be causing a loop. I was also seeing connections to 23.92.31.11 and 198.211.122.90. The wireguard connections were getting the names resolved as well.

**Comment by laserjobs** [comment]
It looks like it was just Windows Process Manager causing the issue. Sorry for the confusion you can close this.
