### ISSUE TITLE
App Window and Process does not close completely - MacOS M1 

### ISSUE THREAD

**Issue by debosmit-git** [Windscribe/Desktop-App#168]
App Window gets stuck each time I try to close Windscribe Desktop App

<img width="1291" alt="image" src="https://github.com/user-attachments/assets/f4232837-f283-4e49-a7c0-b5cb53b6106d">

**OS and app information:**
 - OS: macOS Sonoma Version 14.5 (23F79)
 - App version: 2.10.15

**To Reproduce**
1. Open Windscribe on a M1 MacBook
2. Close it

**Expected behavior**
The process should close in activity monitor and the window should disappear.

**Screenshots**
<img width="1291" alt="image" src="https://github.com/user-attachments/assets/f4232837-f283-4e49-a7c0-b5cb53b6106d">

<img width="1073" alt="image" src="https://github.com/user-attachments/assets/9633bdf8-66f5-4ee7-ba53-4e23fb97d311">

**Additional context**
Does this bug occur in previous versions of the app or is it new to the build version you noted above?

It occured in previous versions since MacOS ARM port.

**Comment by bernerdad** [comment]
Hi, and thanks for the bug report.  This should be fixed in our next guinea pig release (2.11.7).  I'll tag you here when it is available for your validation.  Cheers!

**Comment by bernerdad** [comment]
This should be resolved now with the new [release](https://github.com/Windscribe/Desktop-App/releases/tag/v2.11.7).  Please let us know if the issue still occurs with this 2.11.7 release.  Thanks!
