### ISSUE TITLE
Skip programs, domains or ips traffic to being routed in the VPN

### ISSUE THREAD

**Issue by Armiixteryx** [Windscribe/Desktop-App#17]
Hello,

Thanks for the new application version looks very cool!

I want AWS Workspace to run directly, without route its traffic through the VPN. Is there an option to configure Windscribe for that?

I have also a similar case, where I cannot reach my router configuration at `192.168.x.x` when I have Windscribe activated. Is there a way to put a allow list for selected ips / domains?

**Comment by bernerdad** [comment]
Hi.  To be able to reach your router, and other machines on your LAN, enable the 'Allow LAN traffic' setting in the Windscribe app.

Assuming you are using the AWS Workspaces app, you can configure Windscribe to exclude the app from the VPN tunnel by enabling Windscribe's 'Split Tunneling' feature.

You can also hit up our support team to guide you through this, or any other usage questions you might have:
https://windscribe.com/support

Cheers!

**Comment by koplo199** [comment]
Hi @bernerdad :wave: 

As Split Tunneling isn't officially supported yet on the Linux application, I was wondering what would currently be the easiest way to manually configure it? (In fact I would be more interested in a 'Reverse Split Tunnelling', a.k.a only using the VPN for a specific set of applications).

I need to do more research, but I saw that it was possible using [network namespace](https://schnouki.net/post/2014/openvpn-for-a-single-application-on-linux/). Do you think it would be a good way of doing it? Let me know if I can help on this feature, as I'll probably experiment with it at some point.

PS: I read somewhere that it also wasn't compatible with UFW (which I'm currently using), what isn't working and what needs to be done to resolve the issue? Let me know if and how I can help on this issue too.

Thanks!

**Comment by bernerdad** [comment]
Please see #100 if anyone is interested in split tunneling on Linux.  Cheers!
