### ISSUE TITLE
Only Updates from safemode

### ISSUE THREAD

**Issue by bufce2010** [Windscribe/Desktop-App#183]
**Describe the bug**
I download the update from GitHub (Guinea Pig) but when I click install it gives an error at 11%
then the app disappears of course
but the folder is there with some files not including the exe files

I must reboot into safe mode with networking and install from there

**OS and app information:**
 - OS: Windows 10 Build19041
 - App version: v2.12.1-alpha

**To Reproduce**
As Described above

**Expected behavior**
Expected to install the update and start the app

**Screenshots**
![image](https://github.com/user-attachments/assets/0207fe8d-0498-45df-9012-e1e98b362f5f)

**Additional context**
Does this bug occur in previous versions of the app or is it new to the build version you noted above?
Yeah, All of previous versions.

**Comment by jaxu** [comment]
Please attach`log_installer.txt` from the installation folder after the installer exits from this error so we can look into this.  Thanks.

**Comment by bufce2010** [comment]
> Please attach`log_installer.txt` from the installation folder after the installer exits from this error so we can look into this. Thanks.

here it is:
[log_installer.txt](https://github.com/user-attachments/files/17257838/log_installer.txt)

**Comment by jaxu** [comment]
Thank you.  We're working on a fix.

**Comment by bernerdad** [comment]
This will be fixed in the next release (2.12.2).  There's also a UI bug here where the text is being truncated in the screenshot you posted.  We've so far been unable to reproduce this.  Would you be able to tell us your monitor settings (display resolution, scale factor, GPU)?  Thanks!

**Comment by bufce2010** [comment]
Display Resolution: 1920*1080
Scale Factor: 100%
GPU: ASUS GTX 1660 OC

*Additional Info:
Monitor: Samsung Odyssey G3 24 inch
Refresh rate: 144Hz

**Comment by bufce2010** [comment]
> This will be fixed in the next release (2.12.2). There's also a UI bug here where the text is being truncated in the screenshot you posted. We've so far been unable to reproduce this. Would you be able to tell us your monitor settings (display resolution, scale factor, GPU)? Thanks!

An Additional info that might save you a lot of time regarding the truncated text:
I've edited font size using "Winaero Tweaker" tool, this could be the reason

**Comment by bufce2010** [comment]
> This will be fixed in the next release (2.12.2). There's also a UI bug here where the text is being truncated in the screenshot you posted. We've so far been unable to reproduce this. Would you be able to tell us your monitor settings (display resolution, scale factor, GPU)? Thanks!

Display Resolution: 1920*1080
Scale Factor: 100%
GPU: ASUS GTX 1660 OC

*Additional Info:
Monitor: Samsung Odyssey G3 24 inch
Refresh rate: 144Hz

An Additional info that might save you a lot of time regarding the truncated text:
I've edited font size system-wide using "Winaero Tweaker" tool, this could be the reason

**Comment by bernerdad** [comment]
This has been fixed in the [2.12.2](https://github.com/Windscribe/Desktop-App/releases/tag/v2.12.2) release.  Please let us know if you are still able to reproduce this issue with the new release.  Thanks!

**Comment by bufce2010** [comment]
> This has been fixed in the [2.12.2](https://github.com/Windscribe/Desktop-App/releases/tag/v2.12.2) release. Please let us know if you are still able to reproduce this issue with the new release. Thanks!

I've Successfully updated the app, thanks.
