### ISSUE TITLE
Proxy header error

### ISSUE THREAD

**Issue by unknown--** [Windscribe/Desktop-App#185]
**Describe the bug**
When using the HTTP proxy I sometimes get requests that don't go through with the error being "400 Bad Request". To be sure I've tried other proxy programs in conjunction with Windscribe being connected and they have no problem making the request.

**OS and app information:**
 - OS: Microsoft Windows [Version 10.0.19045.4780]
 - App version: 2.11.11

**To Reproduce**
1. The following URL requires being connect to a Canadian server for geoblock reasons
2. `curl -s --max-time 20 "http://capi.9c9media.com/destinations/ctvthrowback_hub/platforms/desktop/contents/2927760/contentpackages/6725891/manifest.mpd" -x <windscribe_proxy_address> -v`

**Expected behavior**
The connection should pass through without an error

**Additional context**
Older versions had this problem too

**Comment by bernerdad** [comment]
Thanks for the bug report.  We'll investigate the issue and report back here when a resolution is available.  Cheers!

**Comment by bernerdad** [comment]
Hi.  This should be fixed in this [release](https://github.com/Windscribe/Desktop-App/releases/tag/v2.12.3).  Cheers!
