### ISSUE TITLE
windscribe-cli - openSUSE Tumbleweed - Failed to connect to bus: No medium found

### ISSUE THREAD

**Issue by thor0215** [Windscribe/Desktop-App#187]
**Describe the bug**
Running openSUSE with minimal install and headless. Installed windscribe-cli 2.11.11 and it will not run. It is giving the error:
Failed to connect to bus: No medium found
Could not start application

**OS and app information:**
 - OS: openSUSE Tumbleweed
 - App version: windscribe-cli-2.11.11-0.x86_64

**To Reproduce**
1. Install windscribe-cli on openSUSE Tumbleweed using MicroOS pattern
2. install windscribe-cli
3. run winscribe-cli login username 'password'
Failed to connect to bus: No medium found
Could not start application

**Expected behavior**
Expect it to login

**Comment by jaxu** [comment]
Same as #188, please try again after `systemctl start windscribe-helper`

**Comment by bernerdad** [comment]
This has been fixed in the [2.12.2](https://github.com/Windscribe/Desktop-App/releases/tag/v2.12.2) release.  Please let us know if the new release resolves this issue for you.  Thanks!

**Comment by thor0215** [comment]
This looks like a systemd user issue. I'll go ahead and close this for now.
