### ISSUE TITLE
windscribe-cli - openSUSE Tumbleweed - Aborting: app did not start in time

### ISSUE THREAD

**Issue by thor0215** [Windscribe/Desktop-App#188]
**Describe the bug**
Running openSUSE Tumbleweed with KDE. Attempting to log in using windscribe-cli I get this error: Aborting: app did not start in time

**OS and app information:**
 - OS: openSUSE Tumbleweed with KDE
 - App version 2.11.11

**To Reproduce**
1. Install windscribe-cli
2. Run windscribe-cli login username password
3. See error
Aborting: app did not start in time

**Expected behavior**
Expect windscribe-cli to log in.

**Comment by jaxu** [comment]
Apologies, this is a missing line in the install script.  Please run `systemctl start windscribe-helper`.  We'll fix this in an upcoming build.

**Comment by thor0215** [comment]
That fixed this issue
