### ISSUE TITLE
Some of the translation keys are missing!

### ISSUE THREAD

**Issue by MedicalJewel105** [Windscribe/Desktop-App#192]
While improving translations I came across some untranslatable lines.

`Settings/General`
Update Channel values do not have translations (btw what does ‘Guinea Pig’ mean?)
![image](https://github.com/user-attachments/assets/a1b18f29-e81c-443e-a98f-3afc19818a99)

`Settings/R.O.B.E.R.T.`
Same.
![image](https://github.com/user-attachments/assets/ed6e476c-7147-4747-9a20-6030298d4d66)

**OS and app information:**
 - OS: Windows 10
 - App version 2.11.11

**Comment by jaxu** [comment]
Thanks.  Guinea pig here means "Experimental".

The keys for Release/Beta will be restored soon.

The strings in the ROBERT screen are currently not translatable because they come from the server.  We may add these at a later date.
