### ISSUE TITLE
Windscribe_cli v2.11.11 defaults to wireguard when I reconnect or restart

### ISSUE THREAD

**Issue by willhubs** [Windscribe/Desktop-App#194]
**Describe the bug**
After logging in, I connect using "windscribe_cli connect somelocation udp".  Everything checks out fine with "windscribe_cli status", if I disconnect for any reason and reconnect it will start a wireguard connection.

**OS and app information:**
Ubuntu 24.04 and 24.10
Windscribe_cli v2.11.11

**To Reproduce**
connect to server with udp
disconnect or reboot
connects but now connected with wireguard

**Expected behavior**
Should connect as UDP as that was the last connection.

[General]
Language=en
LaunchOnStartup=true
UpdateChannel=Release

[Advanced]
APIResolutionAddress=
APIResolutionMode=Auto
DNSManager=Auto
DNSPolicy=Cloudflare
IgnoreSSLErrors=false

[Connection]
AllowLANTraffic=true
Autoconnect=true
AutosecureNetworks=true
CircumventCensorship=false
ConnectedDNSMode=Auto
ConnectedDNSUpstream1=
ConnectedDNSUpstream2=
ConnectionMode=Auto
FirewallMode=Auto
FirewallWhen=Before Connection
ManualConnectionPort=443
ManualConnectionProtocol=UDP
PacketSizeMTU=-1
PacketSizeMode=Auto
ProxyAddress=
ProxyMode=None
ProxyPassword=
ProxyPort=0
ProxyUsername=
ShareProxyGatewayEnabled=false
ShareProxyGatewayMode=HTTP
ShareProxyGatewayPort=0
SplitDNS=false
SplitDNSHostnames=
SplitTunnelingApps=
SplitTunnelingEnabled=false
SplitTunnelingMode=Exclude
SplitTunnelingRoutes=

[Networks]
mywifinetworkssid\NetworkTrustType=Secured

**Comment by jaxu** [comment]
Thanks for the report.  This appears to be a bug and will be addressed in a future build.

**Comment by jaxu** [comment]
Closing since this appears to be a configuration error.
