### ISSUE TITLE
Windscribe_cli v2.11.11 status shows firewall off even after turning firewall to on instead of auto.

### ISSUE THREAD

**Issue by willhubs** [Windscribe/Desktop-App#195]
When disconnecting from a connection, the firewall status says off even if I have turned/set the firewall to ON instead of auto.

**OS and app information:**
Ubuntu 24.04 and 24.10
Windscribe_cli v2.11.11

**To Reproduce**
windscribe_cli login "username" "password" [2FA code]
windscribe_cli firewall on
windscribe_cli connect troll udp
windscribe_cli status
> Internet connectivity: available
> Login state: Logged in
> Firewall state: On
> Connect state: Connected: Troll - Station
> Protocol: UDP:443
> Data usage: 1.0 GB / Unlimited
windscribe_cli disconnect
windscribe_cli status
> Internet connectivity: available
> Login state: Logged in
> Firewall state: Off
> Connect state: Disconnected
> Data usage: 1.0 GB / Unlimited

**Expected behavior**
If the firewall is turned on, it should stay on regardless of being connected and should reflect that status properly.

I have also tried changing the firewall from AUTO to ON in my windscribe_cli.conf and it will just revert back to AUTO.

$ cat .config/Windscribe/windscribe_cli.conf 
[General]
Language=en
LaunchOnStartup=true
UpdateChannel=Release

[Advanced]
APIResolutionAddress=
APIResolutionMode=Auto
DNSManager=Auto
DNSPolicy=Cloudflare
IgnoreSSLErrors=false

[Connection]
AllowLANTraffic=true
Autoconnect=true
AutosecureNetworks=true
CircumventCensorship=false
ConnectedDNSMode=Auto
ConnectedDNSUpstream1=
ConnectedDNSUpstream2=
ConnectionMode=Auto
FirewallMode=Auto
FirewallWhen=Before Connection
ManualConnectionPort=443
ManualConnectionProtocol=UDP
PacketSizeMTU=-1
PacketSizeMode=Auto
ProxyAddress=
ProxyMode=None
ProxyPassword=
ProxyPort=0
ProxyUsername=
ShareProxyGatewayEnabled=false
ShareProxyGatewayMode=HTTP
ShareProxyGatewayPort=0
SplitDNS=false
SplitDNSHostnames=
SplitTunnelingApps=
SplitTunnelingEnabled=false
SplitTunnelingMode=Exclude
SplitTunnelingRoutes=

[Networks]
mywifinetworkssid\NetworkTrustType=Secured

**Comment by jaxu** [comment]
Thanks for the report.  This is intentional, because your FirewallMode is set to Auto.  If you want the Firewall to retain the state you set, please set it to Manual.
