### ISSUE TITLE
Guineapig v2.13.3 - Custom Wireguard config connects but "wireguard" and "51820" keep blinking

### ISSUE THREAD

**Issue by wellloaded** [Windscribe/Desktop-App#196]
It seems to connect fine, but the blinking text doesn't look right.
I left it overnight and it still blinks. Disconnecting/rebooting/etc doesn't fix.

It appears to be connected, although admittedly the previously working port forwarding from a 3rd party PVN provider doesn't redirect ports, so I'm wondering if the two issues are connected.

**Comment by jaxu** [comment]
Please use the bug report template if you are reporting a bug.  For issues like this we need a debug log from you as well.

**Comment by bernerdad** [comment]
Please re-open the ticket if this is still an issue in the latest [alpha release](https://github.com/Windscribe/Desktop-App/releases/tag/v2.13.3).
