### ISSUE TITLE
Autoconnect option doesnt automatically connect after system start

### ISSUE THREAD

**Issue by Ramazzzzan** [Windscribe/Desktop-App#203]
**Describe the bug**
Autoconnect option doesnt automatically connect after system start

**OS and app information:**
 - OS: Ubuntu 24.04.1-server-amd64
 - App version windscribe-cli 2.12.7 amd64

**To Reproduce**
1. Edit ~/.config/Windscribe/windscribe_cli.conf to ensure LaunchOnStartup=true and Autoconnect=true
2. connect to server eg windscribe-cli connect Tulip, check if its connected
3. sudo shutdown -r
4. after reboot windscribe-cli doesnt connect automatically

**Expected behavior**
I expect windscribe-cli to automatically connect to latest server after pc reboot

**Screenshots**
windscribe-cli status output:
1) right after reboot: 
Internet connectivity: available
Login state: Logging in
Firewall state: Off
Connect state: Disconnected
2) in 10 sec after reboot and all the times after that:
Internet connectivity: available
Login state: Logged in
Firewall state: Off
Connect state: Disconnected
Data usage: 692.35 GB / Unlimited

**Additional context**
i tried reinstalling both latest stable and alpha. no luck.

Here is "~/.config/Windscribe/windscribe_cli.conf"

`[General]
Language=en
LaunchOnStartup=true
UpdateChannel=Release

[Advanced]
APIResolutionAddress=
APIResolutionMode=Auto
DNSManager=Auto
DNSPolicy=Cloudflare
IgnoreSSLErrors=false

[Connection]
AllowLANTraffic=true
Autoconnect=true
AutosecureNetworks=true
CircumventCensorship=true
ConnectedDNSMode=Auto
ConnectedDNSUpstream1=
ConnectedDNSUpstream2=
ConnectionMode=Auto
FirewallMode=Auto
FirewallWhen=Before Connection
MACAddressSpoofingAddress=
MACAddressSpoofingAutoRotate=false
MACAddressSpoofingEnabled=false
MACAddressSpoofingInterface=No Interface
ManualConnectionPort=443
ManualConnectionProtocol=WireGuard
PacketSizeMTU=-1
PacketSizeMode=Auto
ProxyAddress=
ProxyMode=None
ProxyPassword=
ProxyPort=0
ProxyUsername=
ShareProxyGatewayEnabled=false
ShareProxyGatewayMode=HTTP
ShareProxyGatewayPort=0
ShareProxyGatewayWhileConnected=false
SplitDNS=false
SplitDNSHostnames=
SplitTunnelingApps=
SplitTunnelingEnabled=false
SplitTunnelingMode=Exclude
SplitTunnelingRoutes=`

**Comment by jaxu** [comment]
This has been discussed in #200.  It will be fixed next release.

**Comment by bernerdad** [comment]
This is resolved in the [2.13.3 release](https://github.com/Windscribe/Desktop-App/releases/tag/v2.13.3).
