### ISSUE TITLE
Cannot skip TAP driver installation during silent install

### ISSUE THREAD

**Issue by brogers5** [Windscribe/Desktop-App#22]
Version: 2.3.16, Windows

When I invoke the installer with the `-silent` command-line argument, a dialog is still shown prompting the user to allow installation of the TAP driver:

![image](https://user-images.githubusercontent.com/6869577/153771229-a74ce79e-399f-47b0-bf76-06b1d778ec5c.png)

This poses a challenge for completely automated installations, as the installer will block on this step and requires human intervention to accept the driver install.

In pre-2.0 versions, there was a `/NODRIVER` command-line argument that effectively delayed the install of the TAP driver until runtime. Are there any plans to reintroduce this feature?

**Comment by bernerdad** [comment]
Hi.  Thanks for the regression report.  We've added it to our engineering board.  Cheers!

**Comment by bernerdad** [comment]
We've added a command-line parameter to skip TUN/TAP driver installation.  The new build (v2.5.1) is available in our guinea pig channel.
