### ISSUE TITLE
[Bug] iptables conflict with Docker

### ISSUE THREAD

**Issue by deyanginev** [Windscribe/Desktop-App#25]
Hi team,

I have recently installed the GUI app on Ubuntu 20.04 alongside Docker (20.10.12, build e91ed57). When started, Docker defines a bunch of `iptables` rules which Windscribe resets when connected. I have uninstalled Windscribe GUI and tried using the CLI which seems to correctly restore the `iptables` rules when disconnected.

Let me know if further details are needed here.

Deyan

**Comment by bernerdad** [comment]
Hi Deyan.  Thanks for the bug report.  Once an engineer is assigned to it, we'll reach out to you if any further details are required.

**Comment by atchik6056** [comment]
same, Ubuntu 18.04.6 LTS, Docker version 20.10.13, windscribe_2.3.15_beta_amd64.deb
winscribe screwed iptables, so letsencrypt/reversed proxy containers stopped working, blocking everything going via them
uninstalled windscribe_2.3.15_beta_amd64.deb, iptables is not recovered
disappointing
now I need to figure out how to recover it, manually, pain...

**Comment by bernerdad** [comment]
Hi. Apologies for allowing this issue to languish for so long.  Can you please try this build and let us know if the IP tables conflict is still occurring? Thanks!
https://deploy.totallyacdn.com/desktop-apps/2.6.12/windscribe_2.6.12_guinea_pig_amd64.deb
