### ISSUE TITLE
[Request] Official build for Opensuse

### ISSUE THREAD

**Issue by mystic-githuber** [Windscribe/Desktop-App#28]
There is literally no official VPN app for Opensuse apart from NordVPN, yikes!

Opensuse has been around as long as Ubuntu and us users have to go by using openvpn from every other major VPN provider. 

Its also supports .rpm builds. So, please build an official app for Opensuse, if its only for the Tumbleweed version its good enough!

**Comment by yegors** [comment]
We'll look into offering an official package, however, are you able to use Yast to install the RPM? https://yast.opensuse.org/

**Comment by mystic-githuber** [comment]
@yegors 

Yes, it works without any problem. Perhaps some more testing should be done, I am not a software dev so I am not sure what to look for.

**Comment by mystic-githuber** [comment]
@yegors 

By the way, I have gone as far as only installing the app alone. I haven't played around with connecting to different servers since I am not a Windscribe customer.

**Comment by yegors** [comment]
You can load custom OpenVPN and WG configs into the app, without a Windscribe account (which is free btw).

**Comment by FredB750** [comment]
I'm on opensuse leap and I would also like a working gui app.
The app installs and seems to run OK until you turn it on. Can't connect , some resolve error?

**Comment by bernerdad** [comment]
Hi.  v2.5.6 is available in our guinea pig channel, and should resolve this issue.  Cheers!

**Comment by linuxtopia** [comment]
I cannot connect to internet when I try to login on Leap 15.5. We need official build for OpenSUSE

**Comment by bernerdad** [comment]
> I cannot connect to internet when I try to login on Leap 15.5. We need official build for OpenSUSE

We've improved OpenSUSE compatibility in our latest guinea pig build.  It's not an official OpenSUSE build, but we are looking into making one at a later date.  Please let us know if this build works better for you on Leap 15.5.

https://deploy.totallyacdn.com/desktop-apps/2.10.2/windscribe_2.10.2_guinea_pig_x86_64.rpm
