### ISSUE TITLE
[Bug?] Not working at all on Debian

### ISSUE THREAD

**Issue by nicolabaesso** [Windscribe/Desktop-App#29]
Opening this issue because I didn't find the answer on other issues. Also I'm labelling this as a "bug?" because I don't really know if it's only on my machines.

So, when I try to connect to any location, it fails everytime. I tried UDP, Ike and TCP, both via automatic and manual mode. I also tried with the Docked mode on and off.

OS  & app verison I have this issue
- Debian 11 Bullseye & Windscribe v2.4.1
- Q4OS Centaurus (based on Debian 10 Buster) & Windscribe v2.3.15 (latest release)

Below the steps I made:

Q4OS
- Download file from Windscribe website
- Installed via dpkg command
- Log In
- Can't connect
- Tried with Windscribe CLI (already installed): worked on Switzerland server (not on US server, it was the day US servers didn't work)
- Uninstalled both version (GUI and CLI) as it was suggested not to keep the CLI version
- Re-install of GUI version
- Still can't connect

Debian
- Cloned the repository
- Followed istruction for build
- Installed the brand new .deb file
- Log In
- Can't connect either
- Recover and install the old CLI, as in Q4OS worked
- API error and can't connect, followed by uninstall of CLI version

To be fair, on Q4OS I also tried the browser extension on Brave (Chrome based) and autopilot mode worked, but I still couldn't connect to "chosen" server.

If you need more informations, reach me out!

**Comment by bernerdad** [comment]
Hi.  Thanks for the bug report.  We'll give Debian 11 a spin and reach out to you if we cannot reproduce the issue.  Cheers!

**Comment by bernerdad** [comment]
Confirmed to work in Debian 11.3 using our latest version (2.4.5).  Please update to that version via the guinea pig update channel and let us know if it works for you.  Thanks!

**Comment by nicolabaesso** [comment]
Worked on my Debian 11 installation! I will edit this comment when I try it on Q4OS, but it should work. Thank you for your support!
