### ISSUE TITLE
Prevent launching of Windscribe if `-silent` is passed on the command-line

### ISSUE THREAD

**Issue by joachimschmidt557** [Windscribe/Desktop-App#30]
Currently, the installer launches Windscribe after the installation process has completed even when the `-silent` flag was passed on the command-line. This prevents the installer from easily being used in package managers such as chocolatey (I am the maintainer of the Windscribe chocolatey package): The installation process [hangs](https://gist.github.com/choco-bot/4b80de207279f60f241a0103b320327a#file-install-txt-L399) as the Windscribe application is still open.

Not launching the application after the installation process when `-silent` is provided would prevent ugly hacks such as waiting for a set period of time and then killing the Windscribe application.

**Comment by bernerdad** [comment]
Hi.  Thanks for the feature request.  We've added it to our engineering board.
