### ISSUE TITLE
windscribe-cli: wrong library location

### ISSUE THREAD

**Issue by reneeotten** [Windscribe/Desktop-App#31]
on macOS, `windscribe-cli` won't start (both for v2.3.16 DMG from the website and v2.4.1 from GithHub) because the directory for the protobuf library is wrong.

```
 % otool -L windscribe-cli
windscribe-cli:
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1894.60.100)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1069.24.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59306.140.5)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 1061.141.1)
	/Users/aaa/Documents/client-desktop/build-libs/protobuf/lib/libprotobuf.28.dylib (compatibility version 29.0.0, current version 29.3.0)
	@rpath/QtGui.framework/Versions/5/QtGui (compatibility version 5.12.0, current version 5.12.11)
	@rpath/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.12.0, current version 5.12.11)
	@rpath/QtCore.framework/Versions/5/QtCore (compatibility version 5.12.0, current version 5.12.11)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 52.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1677.104.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

instead of ```/Users/aaa/Documents/client-desktop/build-libs/protobuf/lib/libprotobuf.28.dylib``` this should probably be ```@executable_path/../Frameworks/libprotobuf.28.dylib``` as it is for the `Windscribe` executable.

**Comment by bernerdad** [comment]
Hi.  Apologies for our fumble on that one.  If you install v2.3.16 from the website and set your update channel to 'guinea pig', you'll get v2.4.2 which has this issue fixed.  Cheers!

**Comment by reneeotten** [comment]
thanks @bernerdad. I would be happy to try that but the reason I started poking around a bit in the packages is that I cannot get it to open the Gui window anymore. I installed v2.3.16 this morning when I noticed the update, that worked all fine and it started as expected. After that I set the option "Start minimized" (or something along these lines); it does open up and I see the icon in the menu-bar; however, clicking on it doesn't do anything and I cannot get the Windscribe gui. Completely uninstalling and re-installing didn't help, but I might have missed some configuration file (though I did an uninstall through CleanMyMac, so it should have removed everything...). Any suggestions would be appreciated, I am of course happy to provide more information/diagnostics if you tell me how/what.

**Comment by bernerdad** [comment]
Hi Renee.  After making sure the Windscribe app is not running, check for a `com.windscribe.Windscribe2.plist` file in `/Users/[your account]/Library/Preferences`.  Delete it if it's there, then start the Windscribe app back up.  If after this you're still having problems with the app, please open a ticket with our support team.  Thanks!

https://windscribe.com/support

**Comment by reneeotten** [comment]
@bernerdad - your suggestion to remove the Preferences did the trick and the update to v1.4.2 resolved the library path issue. Thanks for the quick responses!
