### ISSUE TITLE
GUI broken on wayland

### ISSUE THREAD

**Issue by Nuc1eoN** [Windscribe/Desktop-App#35]
On wayland the GUI has is quite unusable, some buttons do not work (eg close, minimize), parts of the gui freeze, very difficult to drag the window.

Investigating I have noticed that on my system it uses xwayland.

So I tried launching it with `QT_QPA_PLATFORM=wayland`, it shows:
```shell
QT_QPA_PLATFORM=wayland /opt/windscribe/Windscribe
[{gmt_time}      0.000] [qt.qpa.plugin]	Could not find the Qt platform plugin "wayland" in ""
[{gmt_time}      0.000] [default]	This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

zsh: IOT instruction (core dumped)  QT_QPA_PLATFORM=wayland /opt/windscribe/Windscribe

```
Other QT apps like dolphin work fine for me and natively under wayland.

**Comment by Nuc1eoN** [comment]
Hello, I still have the issue with the latest version.

**Comment by Nuc1eoN** [comment]
>In the short term, you could grab the plugin from the Qt 5.12.11 binary packages available from the Qt website. The plugin goes in the /usr/local/windscribe/plugins/platforms folder.

I am struggling to find such binary packages. There is only https://www.qt.io/offline-installers and it points to a binary graphical installer, and the installer even requires me to register on qt.io.

Would you be able to upload a zip with the necessairy files?

**Comment by bernerdad** [comment]
Hi.  v2.5.6 is available in our guinea pig channel, and adds full wayland support to the app.  Please give it a try and reopen this ticket if the wayland issues are not resolved.  Cheers!

**Comment by Nuc1eoN** [comment]
Hi, where or what is the guinea pig channel?

**Comment by bernerdad** [comment]
There is an "Update Channel" setting in the app's preferences.  You can set this to "Guinea Pig", and the app should then detect the new version.  Here's a link to the Debian package just in case that doesn't work for you:
https://assets.totallyacdn.com/desktop/beta/windscribe_2.5.6_guinea_pig_amd64.deb

**Comment by Nuc1eoN** [comment]
Thank you the .deb version worked for me.
