### ISSUE TITLE
when i turn off windscribe my normal connection fail (no internet access)

### ISSUE THREAD

**Issue by sianami** [Windscribe/Desktop-App#40]
Hi
when i turn off windscribe my normal connection fail and show (no internet access)
before it was working, now i have this issue
uninstalling windscribe didnt work too
what is problem?how fix it?
![image](https://user-images.githubusercontent.com/68529832/163760821-86ffee37-8e6e-475e-b293-ef3404a4e5a3.png)

**Comment by bernerdad** [comment]
Hi.  Please contact our support group and they'll assist you in resolving the issue.  Thanks!
https://windscribe.com/support

**Comment by sianami** [comment]
issue fixed
it was DNS problem
i changed alternate DNS to 5.200.200.200 and issue fixed
![image](https://user-images.githubusercontent.com/68529832/163862532-e1815f8c-aaa3-45b0-8175-ce2d5edeaa5d.png)
