### ISSUE TITLE
[feature request] please add reset all settings to default

### ISSUE THREAD

**Issue by sianami** [Windscribe/Desktop-App#42]
hi
sometimes i change many settings and later its very hard to find and undo changed settings to default
adding a button to reset all settings to default can be helpful

**Comment by bernerdad** [comment]
Hi.  We are adding this feature to the installer.  We'll update this ticket when the feature is available in our guinea pig update channel.

**Comment by yegors** [comment]
In the mean time, on Windows, you can simply remove `HKEY_CURRENT_USER\SOFTWARE\Windscribe\Windscribe2` from your registry. On a Mac, you can remove the plist file.

**Comment by bernerdad** [comment]
We've added a 'factory reset' option to the Windows and macOS installers. The new build (v2.5.1) is available in our guinea pig channel.
