### ISSUE TITLE
Windows: Can filters with a hard permit on a higher weight sublayer override blocks by Windscribe's?

### ISSUE THREAD

**Issue by ltguillaume** [Windscribe/Desktop-App#44]
A while ago, [simplewall](https://github.com/henrypp/simplewall), basically a front-end for the WFP, had an issue that allowed specific filters (i.e. hard permit, higher weight sublayer) to override its block rules: https://github.com/henrypp/simplewall/issues/689

For simplewall, this has been fixed by using a high sublayer weight and Veto filters (which cannot be overridden). This was done by adding the `FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT` flag to the block filters, which in effect clears the `FWPS_RIGHT_ACTION_WRITE` flag (see https://github.com/henrypp/simplewall/commit/2b7a4a849f76f819b6ac45d468fbfe79b40b668a).

I was wondering whether the (block) rules created for Windscribe's sublayer could be vulnerable to the same overrides that plagued simplewall.

I found some things that might need to be revisited:
1. The applied weight to the sublayer is `0x100` https://github.com/Windscribe/Desktop-App/blob/49bca5b806a66354b5d2a5fd5573fd9580e46be5/backend/windows/windscribe_service/firewallfilter.cpp#L38
  In comparision, simplewall uses the highest possible weight of `0xFFFF`.

2. The only flag applied to Windscribe's filter is `FWPM_SUBLAYER_FLAG_PERSISTENT` https://github.com/Windscribe/Desktop-App/blob/49bca5b806a66354b5d2a5fd5573fd9580e46be5/backend/windows/windscribe_service/firewallfilter.cpp#L231
    1. First off, it seems strange to apply a sublayer's flag to a filter. Is this even correct? Should it in fact be `FWPM_FILTER_FLAG_PERSISTENT`?
    1. `FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT` is not applied, so no Veto filters.

Inside the [simplewall issue](https://github.com/henrypp/simplewall/issues/689), you can find a piece of code that allowed for easy testing (it may be rewritten for testing Windscribe's sublayer).

**Comment by ltGuillaume** [comment]
So no one is gonna have a look at this? @bernerdad

**Comment by ltGuillaume** [comment]
@bernerdad well that didn't work I guess?

**Comment by bernerdad** [comment]
Hi.  We haven't had the bandwidth to look at this one yet.  The ticket remains open and should be worked on for the next release (2.6).

**Comment by bernerdad** [comment]
This issue has been corrected in our v2.6 build, available here: https://windscribe.com/changelog/windows

**Comment by ltGuillaume** [comment]
Great, but I didn't see anything in the changelog that's related to it. I sincerely hope you'll update this repo more often from now on. I would have loved to see the corresponding commit.

**Comment by bernerdad** [comment]
We currently only update this repo when a version is released to the `release` update channel.  Unfortunately, a technical issue prevented us from mirroring the v2.5 release to here.  v2.6 will be mirrored here, likely within the next 3-4 weeks.

**Comment by ltGuillaume** [comment]
Thanks! I hope I'll find be able to find the commit then, though.

**Comment by bernerdad** [comment]
Latest production code is now available for your perusal.  Apologies for the interminable wait.

**Comment by ltguillaume** [comment]
Thanks! Following the point in the opening post:
1. So, I see that `subLayer.weight` has been changed 🙂
2. I see no changes with regard to these points:
    1. I may be wrong about this, but I still think it looks like a sublayer flag is applied to a filter, so I'm not sure if this makes sense at all. Basically, I'd just like to know if it was looked at and if I was just wrong about this (ideally with an explanation why).
    2. I'm not sure if veto rules (i.e. using `FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT`) would make sense here, but I'd love to hear your take on this.

**Comment by jaxu** [comment]
> Thanks! Following the points in the opening post:
> 
>     1. So, I see that `subLayer.weight` has been changed 🙂
> 
>     2. I see no changes with regard to these points:
>        
>        1. I may be wrong about this, but I still think it looks like a sublayer flag is applied to a filter, so I'm not sure if this makes sense at all. Basically, I'd just like to know if it was looked at and if I was just wrong about this (ideally with an explanation why).
>        2. I'm not sure if veto rules (i.e. using `FWPM_FILTER_FLAG_CLEAR_ACTION_RIGHT`) would make sense here, but I'd love to hear your take on this.

Hey there.  Can you point out where we are applying a sublayer flag to a filter?  As far as I can see we have replaced all of the instances of `FWPM_SUBLAYER_FLAG_PERSISTENT` with `FWPM_FILTER_FLAG_PERSISTENT` except where we are actually applying the flag to a `FWPM_SUBLAYER0`.  Most of the calls to add a filter go through this function:

https://github.com/Windscribe/Desktop-App/blob/ff803463b3c348a468152238d3100f74ed836409/backend/windows/windscribe_service/utils.cpp#L362

In particular you may be interested in this block, which also sets the veto flag for block rules:

https://github.com/Windscribe/Desktop-App/blob/ff803463b3c348a468152238d3100f74ed836409/backend/windows/windscribe_service/utils.cpp#L382-L388

**Comment by ltguillaume** [comment]
@jaxu You're totally right, sorry about that! I must have messed up looking through the files in the GitHub UI, which is imho a bit messy. I checked again by cloning the repo and then doing some searches. Everything seems to be implemented as you said. Thanks again! Closing this issue now 🙂
