### ISSUE TITLE
Connection Problem in Ubuntu 22.04

### ISSUE THREAD

**Issue by fakhamatia** [Windscribe/Desktop-App#46]
I had Ubuntu 21.10 and Windscribe v2.3.15(Beta) work fine and fast.
After upgrade to 22.04 Windscribe not connecting at all and after trying and fail my OS internet is brake and noting work and show DNS error in chrome. I have to reboot the system to work internet again.
I remove Windscribe and install again, but not working.

**Comment by yegors** [comment]
Get the latest beta from Guinea Pig channel, or install manually from here: https://windscribe.com/changelog/linux_deb
