### ISSUE TITLE
Tray icon bugged on Deepin

### ISSUE THREAD

**Issue by raspin0** [Windscribe/Desktop-App#47]
https://user-images.githubusercontent.com/39202451/168915391-63b3fb79-c089-46dc-9b37-7e4b2a96e7df.mp4

The video shows the issue. 

OS: Deepin 20.5

**Comment by yegors** [comment]
Did v2.4.7 (from Guiania Pig update channel) fix the issue for you?

**Comment by raspin0** [comment]
> Did v2.4.7 (from Guiania Pig update channel) fix the issue for you?

Unfortunately, no.

**Comment by bernerdad** [comment]
Hi.  v2.5.6 is available in our guinea pig channel.  Could you please give it a try and let us know if it resolves this issue?  Cheers!

**Comment by raspin0** [comment]
Hello, thank you for investigating the issue. Unfortunately after updating to guinea pig I'm unable to turn on Windscribe. The issue seems to be caused by outdated glibc shipped by deepin.
![obraz](https://user-images.githubusercontent.com/39202451/192058539-0efa729f-88ca-4192-bfbc-8b4c42045aa8.png)
