### ISSUE TITLE
RPM package is broken on modern Fedora.

### ISSUE THREAD

**Issue by GabTheBab** [Windscribe/Desktop-App#48]
`error: Importing package 'windscribe': Analyzing /usr/local/windscribe/Windscribe: Unsupported path; see https://github.com/projectatomic/rpm-ostree/issues/233
`
Mullvad had a similar issue that they fixed. https://github.com/mullvad/mullvadvpn-app/issues/1861

**Comment by bernerdad** [comment]
Does v2.4.7 from our Guinea Pig update channel fix the issue for you?

**Comment by GabTheBab** [comment]
Is this different from the beta release on the website? `windscribe_2.4.8_beta_x86_64.rpm` If so, where do I grab this release?

**Comment by bernerdad** [comment]
Hi.  Which version of Fedora are you running on?  Fedora 35 and 36 do not appear to exhibit this issue for us.  Thanks!

**Comment by GabTheBab** [comment]
F36, Fedora Silverblue

**Comment by GabTheBab** [comment]
It uses rpm-ostree instead of dnf. https://github.com/projectatomic/rpm-ostree/issues/233  This is the issue the rpm package hits.

**Comment by GabTheBab** [comment]
Any news on this? The latest 2.4.11 RPM still doesn't work.

**Comment by tutacat** [comment]
RPM is not installing /etc/windscribe directory

**Comment by m2jest1c** [comment]
Hey @GabTheBab, Windscribe 2.6.5 (Guinea Pig) now installs to `/opt`. I cannot test on Silverblue as of right now, but maybe give it a shot and see what happens?
