### ISSUE TITLE
Stunnel not extracting

### ISSUE THREAD

**Issue by yusi1** [Windscribe/Desktop-App#49]
(Building from latest Master)

Currently building dependencies for Windscribe and when running `./install_stunnel` stunnel fails to extract:
```
Installing stunnel...
Loading: "vars/stunnel.yml"
Cleaning: "/home/yaslam/.gitcloned/Desktop-App/temp/stunnel"...
Downloading: "stunnel-5.62.tar.gz"
####################################################################################### 100.0%
Extracting: "stunnel-5.62.tar.gz"

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ERROR: Error extracting archive file.
All done: 0 seconds elapsed

```
When checking `temp/stunnel` it does appear to be in the correct format though:
```
stunnel-5.62.tar.gz
``` 

When running `./build_all` it fails because stunnel was not built in the first place.
```
ERROR: Library "stunnel" is not installed.
Deleting secrets...
```

**Comment by bernerdad** [comment]
Our next mirror to this repo will resolve this issue.  In the meantime, please edit your copy of `tools/vars/stunnel.yml` and change the `VERSION_STUNNEL` value to 5.64, then rerun the install_stunnel step.
