### ISSUE TITLE
Windscribe Arch (Mangero)

### ISSUE THREAD

**Issue by maxwell108** [Windscribe/Desktop-App#51]
I made a pkg  using debtap from the .deb .. working  [link](https://icedrive.net/s/kiNQ5FttwfAzzFy61CgFtN7N56TR) 
seeing as it was coming soon long time

**Comment by PRESFIL** [comment]
[windscribe-bin](https://aur.archlinux.org/packages/windscribe-bin)
[windscribe-git](https://aur.archlinux.org/packages/windscribe-git)

**Comment by bernerdad** [comment]
Hi.  We have an official Arch Linux build of the app available in our guinea pig channel.  You can get it here:
https://assets.totallyacdn.com/desktop/beta/windscribe_2.5.6_guinea_pig_x86_64.pkg.tar.zst
Please give it a spin!
