### ISSUE TITLE
Windscribe will not reconnect under a new session if a previous session was terminated while connected.

### ISSUE THREAD

**Issue by voxasz** [Windscribe/Desktop-App#52]
This is on Fedora 36 GNOME, using 2.4.8

To reproduce:
1. Set windscribe to start and connect automatically
2. Connect
3. Log out of GNOME using the user menu
4. Log back in
5. Windscribe will show a tray icon as if it is connecting but won't finish
6. To work around this, exit windscribe, run `systemctl restart windscribe-helper` and run windscribe again; it should connect again.

**Comment by bernerdad** [comment]
Hi.  We've fixed this issue and will post an update here when a new build is available in our guinea pig update channel.

**Comment by bernerdad** [comment]
Hi.  v2.5.6 is available in our guinea pig channel, and it resolves this issue.  Cheers!
