### ISSUE TITLE
[Bug] Always-on firewall Xorg issue in Pop OS

### ISSUE THREAD

**Issue by mystic-githuber** [Windscribe/Desktop-App#53]
When leaving the always-on firewall and having it auto-start on boot, in Xorg the login screen just hangs (breaks). This issue doesn't happen on Wayland.

I have completely disabled Gufw by the way.

I didn't get to test this on another Ubuntu based distribution.

**Comment by bernerdad** [comment]
Hi.  We could not reproduce this issue on Ubuntu 20.04 or newer.  Also tried the latest ZorinOS.

**Comment by mystic-githuber** [comment]
@bernerdad 
Can you give me a support email where I can send you my logs please? I can't post it here since it might have my IP address.

**Comment by bernerdad** [comment]
Hi.  The best thing to do is submit a support ticket.  The support team will collect your logs and coordinate with the development team.  Thanks!
https://windscribe.com/support/ticket

**Comment by bernerdad** [comment]
Thank you for sending your logs to our support team.  We've created a ticket to investigate this issue.  However, Pop OS is not one of our officially supported distributions, so it may take a while before we can look into this.

**Comment by mystic-githuber** [comment]
@bernerdad 
Your welcome dev! For now I am sticking to wayland.

**Comment by bernerdad** [comment]
Hi.  v2.5.6 is available in our guinea pig channel.  Could you please give it a try and let us know if it resolves this issue?  Cheers!

**Comment by mystic-githuber** [comment]
@bernerdad 

Hello dev, yes it seems to be fixed on the latest 2.4.11

**Comment by bernerdad** [comment]
Hi.  Please try our v2.5.6 build and let us know if it resolves the issue.  Thanks!
https://assets.totallyacdn.com/desktop/beta/windscribe_2.5.6_guinea_pig_amd64.deb

**Comment by mystic-githuber** [comment]
@bernerdad 
There is no problem with the boot-up in x.org but now its the shutdown where its getting hanged now....lol.

I will send the debug logs to via the contact form again.

**Comment by bernerdad** [comment]
Another guinea pig build is available: https://windscribe.com/changelog/linux_deb

**Comment by bernerdad** [comment]
Hi.  Can you please try this build and let us know if the hang on shutdown is still occurring?  Thanks!
https://deploy.totallyacdn.com/desktop-apps/2.6.12/windscribe_2.6.12_guinea_pig_amd64.deb
