### ISSUE TITLE
Location load doesn't display on the bottom location

### ISSUE THREAD

**Issue by MandiYang** [Windscribe/Desktop-App#54]
![Screenshot from 2022-06-10 18-38-14](https://user-images.githubusercontent.com/64307609/173112171-d02008ae-d203-432f-9a12-56fd350f2812.png)

The title says it all, I am using Windscribe v2.4.8(Beta) on Ubuntu 22.04

**Comment by bernerdad** [comment]
Thanks!  Our QA team noted the same issue and we will fix it asap.  Cheers!

**Comment by bernerdad** [comment]
Hi.  v2.5.6 is available in our guinea pig channel, and it resolves this issue.  Cheers!
