### ISSUE TITLE
annoying pop-up failing update message that shows up anytime app is started

### ISSUE THREAD

**Issue by tdeseez** [Windscribe/Desktop-App#57]
How to disable this message ? Couldn't find any useful option in the settings dialogs.

"Windscribe could not check for update due to an invalid platform config. You may want to try manually updating your installation."

Thanks/

**Comment by bernerdad** [comment]
Hi.  Which version of the app are you running (2.4.11?), and which Linux distro and version?  Thanks!

**Comment by tdeseez** [comment]
Hi
this is 2.4.11 version running on latest Manjaro (arch linux). The package is from aur repository :

https://aur.archlinux.org/packages/windscribe-bin

thanks.

**Comment by bernerdad** [comment]
We've fixed this issue.  I'll post back here asap when a build is available with the fix.  Cheers!

**Comment by tdeseez** [comment]
That's good news ! Can't wait for next build ! 

Thanks /

**Comment by bernerdad** [comment]
Hi.  We have an official Arch Linux build of the app available in our guinea pig channel.  You can get it here:

**Comment by tdeseez** [comment]
Tried it : works fine ! No annoying popup this time. I like your app. Should be in manjaro reposiories.
Thanks for the fix. Keep on good work.
cheers/
