### ISSUE TITLE
Change /usr/local/bin/windscribe to /usr/bin/windscribe

### ISSUE THREAD

**Issue by tommytran732** [Windscribe/Desktop-App#58]
Currently, the Linux binary gets installed to /usr/local/bin. This is less than ideal for a variety of reasons:
- It's not where it's supposed to be in the Filesystem Heirachy. /usr/local/bin is supposed to be used for binaries compiled by the user themselves, not binaries distributed by a vendor like Windscribe.
- /usr/local/bin does not play well with immutable distributions. This directory does not work with rpm-ostree at all, and as such it would be impossible for Silverblue/Kinoite users to use Windscribe's VPN app. I haven't tested if this works on openSUSE MicroOS yet, but it is guaranteed to break transactional updates on all openSUSE variants. /usr/local/bin is in its own BTRFS subvolume and does not get rolled back along with the rest of the system by Snapper. If a user does a `snapper rollback`, they will end up with a system where the binary in /usr/local/bin is newer than whatever zypper thinks it is.
- This also does not play well with Qubes OS's TemplateVMs. /usr/local/bin is not a persistent directory on Qubes TemplateVMs, and will get lost when the user creates an AppVM based on it.

**Comment by bernerdad** [comment]
Thanks for bringing this to our attention.  The dev team concurs, and we'll hopefully get this rectified for the upcoming 2.5 release.

**Comment by bernerdad** [comment]
The latest v2.6.5 guinea pig build, available here (https://windscribe.com/changelog/linux_deb), now installs to /opt/windscribe.
