### ISSUE TITLE
Windscribe stops and disables firewalld

### ISSUE THREAD

**Issue by MasterKia** [Windscribe/Desktop-App#59]
Why does Windscribe [stop and disable the firewalld during installation](https://github.com/Windscribe/Desktop-App/blob/master/installer/linux/debian_package/DEBIAN/preinst#L20-L28)?

I'm running Fedora 36 KDE.
According to [Fedora docs](https://docs.fedoraproject.org/en-US/quick-docs/firewalld/) considering the benefits of firewalld, I don't think Windscribe completly nuking it is a good thing.

I have had connection problems (the exclamation mark saying "limited connectivity") after installing the Windscribe rpm and I couldn't connect to internet without enabling Windscribe first.

Since then I've manually enabled firewalld again and everything has been okay, and Windscribe does still work (surprisingly).

So it is really necessary to stop and disable firewalld?

I think this issues might be related as well:
https://github.com/Windscribe/Desktop-App/issues/2
https://github.com/Windscribe/Desktop-App/issues/56

https://www.reddit.com/r/Windscribe/comments/k0s4r8/windscribe_ruins_opensuse_install/

**Comment by bernerdad** [comment]
Hi.  The iptables rules created by the Windscribe app will be overridden by firewalld if it is enabled, which is why we disable it.  By enabling firewalld again, you may be leaking traffic out of the tunnel when the Windscribe app is running.

We're unable to reproduce the connection problems (limited connectivity) you mention.  If you can, please send a log to our support team so we can diagnose the issue.  Thanks!

**Comment by MasterKia** [comment]
Shouldn't the sensible approach be to "sudo systemctl disable firewalld" when Windscribe gets enabled and "sudo systemctl enable firewalld" when Windscribe is disabled?

For sudo privilege you could use the policy kit so no need to run Windscribe as root.

**Comment by bernerdad** [comment]
It's a bit trickier than that.  For example, there is the case where the user has the firewall set to 'always on' in the Windscribe app, and the edge case where the Windscribe app crashes.  That being said, we may find an amenable way to coexist with firewalld in a future release.

**Comment by MasterKia** [comment]
With firewalld disabled, isn't the user in danger if Windscribe is off?

**Comment by bernerdad** [comment]
In my experience, you're not in any danger if the machine is already sitting behind a firewall (e.g. home/office router).  If you are roaming around with the machine and connecting to public wifi or a cellular hotspot, then you would want a firewall on... and should be using the Windscribe app in this case to hide all your traffic from the public network.  macOS, as an example, has the firewall off by default.

**Comment by MasterKia** [comment]
> If you are roaming around with the machine and connecting to public wifi or a cellular hotspot, then you would want a firewall on... and should be using the Windscribe app in this case to hide all your traffic from the public network. 

That's good to know.

> macOS, as an example, has the firewall off by default.
I didn't know, that's weird.

Do you know what approaches other VPNs take in this case? Do they disable the firewalld as well?

https://github.com/ProtonVPN/linux-app
https://github.com/mullvad/mullvadvpn-app

**Comment by bernerdad** [comment]
I haven't tried either of those products.
