### ISSUE TITLE
breaks Custom Config

### ISSUE THREAD

**Issue by doadin** [Windscribe/Desktop-App#60]
G [300722 14:21:08:828 449869.896] [connection]	 openvpn process finished before connected to openvpn socket
G [300722 14:21:08:829 449869.897] [connection]	 answer from openvpn process, answer = "Options error: Each 'connection' block must contain exactly one 'remote' directive\r\nUse --help for more information.\r\n"
G [300722 14:21:08:830 449869.898] [connection]	 ConnectionManager::onConnectionError(), state_ = 1 , error = 7

I have a config that has multiple
<connection></connection>
in it populated with remotes but when windscribe loads it into C:\Users\joshb\AppData\Local\Windscribe\Windscribe2\windscribe_temp_config.ovpn

the <connection></connection> no longer have remotes in them.

**Comment by doadin** [comment]
It looks like it does it here: https://github.com/Windscribe/Desktop-App/blob/49bca5b806a66354b5d2a5fd5573fd9580e46be5/client/engine/engine/customconfigs/ovpncustomconfig.cpp#L130 not sure why its done though.

**Comment by yegors** [comment]
This is fixed already in an upcoming build.

**Comment by bernerdad** [comment]
Hi.  v2.5.6 is available in our guinea pig channel, and it resolves this issue.  Cheers!
