### ISSUE TITLE
Consider adding a lazy login feature.

### ISSUE THREAD

**Issue by peymanr34** [Windscribe/Desktop-App#62]
It would be great if the user could login via the web browser.

In my instance, after updating the app, authentication failed and had to logout. Now I can't login anymore but the Firefox extension still works.

**Comment by bernerdad** [comment]
Hi.  Please submit a support ticket so we can figure out why login is failing for you.  Thanks!
https://windscribe.com/support/ticket

**Comment by peymanr34** [comment]
Hi, Thanks for your reply.
It's due to government censorship. Since it's not a Windscribe issue, I don't want to waste your time <3
