### ISSUE TITLE
[Bug] Huge mouse cursor

### ISSUE THREAD

**Issue by imblowfish** [Windscribe/Desktop-App#63]
OS Version: Ubuntu 22.04 with Wayland
Windscribe version: Guinea Pig v2.5.6

There's a problem with the mouse cursor and determining the position of the click.

Expected cursor
![Screenshot from 2022-10-11 04-35-34](https://user-images.githubusercontent.com/28269602/194972682-ce6e0f52-2a68-41df-b28b-b9a13b364ab7.png)

Actual cursor
![Screenshot from 2022-10-11 04-34-56](https://user-images.githubusercontent.com/28269602/194972721-c780f5b8-d4b0-45ea-8eb1-cc453957ee93.png)

I saw the same issue on another laptop with the Telegram desktop app and found this solution which works great here but I need to change the desktop file myself.
https://github.com/alacritty/alacritty/issues/3266

**Comment by bernerdad** [comment]
Hi, and thanks for reporting this!  It appears to be a Qt bug.  We'll monitor the Qt bug report and patch our app when Qt is patched.  Cheers!
https://bugreports.qt.io/browse/QTBUG-87778

**Comment by bernerdad** [comment]
This seems to be fixed in Qt 6.5, which we are now using.  Could you test this guinea pig build and confirm if it resolves the issue for you?
https://deploy.totallyacdn.com/desktop-apps/2.8.1/Windscribe_2.8.1_guinea_pig.exe

**Comment by imblowfish** [comment]
Hello, I don't have any updates on Guinea Pig channel. And also I can't check the file which you attached above. It's `.exe` file, but I'm on Linux

**Comment by bernerdad** [comment]
Ack!  Apologies for the brain fart.  I've corrected the link.  Cheers!

**Comment by imblowfish** [comment]
Looks ilke cursor problem has been fixed
![image](https://github.com/Windscribe/Desktop-App/assets/28269602/7f5d0bee-c4fa-4342-b039-5fbfdc8dd3e4)
![image](https://github.com/Windscribe/Desktop-App/assets/28269602/bf78f663-389e-44f6-8b62-7d29d29d677b)
But still something strange with a boundary at which the application begins to handle to cursor
Also because of these boundaries there is a problem, if you move the WIndscribe window, it may stop handle the click and you should move the window again and after this click will be processed
I'm not sure that this is the same problem
https://github.com/Windscribe/Desktop-App/assets/28269602/9aa0cd34-f00c-4462-86ab-dbb3d6e928f9

**Comment by bernerdad** [comment]
Yes, looks like this boundary issue is an unrelated issue.  We've made a note on our internal board to investigate it.  Thanks!
