### ISSUE TITLE
Windscribe 2.5+ in RHEL/Alma/Rocky 8 (glibc 2.28 vs 2.29)

### ISSUE THREAD

**Issue by ekasprzak** [Windscribe/Desktop-App#65]
Hi, seems like a new version (2.5.11) doesn't work anymore on RedHat 8 based distros.

RHEL8 (and all clones), which is supported till 2029 uses glibc 2.28 and windscribe 2.4 was working there.

New windscribe 2.5 as I understand needs glibc 2.29.

Is the glibc bump because of some specific function or was it bumped just to use new version?
Is there a chance for lowering requirements to glibc 2.28?

**Comment by bernerdad** [comment]
The glibc bump is due to 2.5 being built on Ubuntu 20.04, as required by it now using Qt 6.3.1.  The 2.4 builds were made on Ubuntu 16.04 and use Qt 5.12.11.  The Fedora package is generated from the Debian package.  The team is discussing options to potentially get this working for you.

**Comment by ekasprzak** [comment]
Understood, thanks for the explanation!
I hope it can be done somehow (RHEL/Alma/Rocky/CentOS 8 etc) is going to be used for many years from now on, so I think this would make a lot of potential users happy so fingers crossed ;)

I guess some other possible solution would to be use universal package format like flatpak (or even snap if it would be easier and more realistic if the base is Ubuntu) - in any case - windscribe would work on almost every major Linux distro then.

No idea how hard it would be to put VPN kind of app into flatpak or snap so just throwing the idea for some discussion/consideration.

Thanks again for the explanation and for all your hard work!

**Comment by bernerdad** [comment]
Hi.  We've created an internal ticket to investigate producing the Fedora package on RHEL 8.4, which is the minimum supported version for Qt 6.3.  It may take us awhile to get to it though.

**Comment by bernerdad** [comment]
Hi.  Our latest guinea pig build should work on RHEL 8.4+/Fedora 29+.  Please give it a spin and let us know if it works for you.  Thanks!
https://deploy.totallyacdn.com/desktop-apps/2.6.5/windscribe_2.6.5_guinea_pig_x86_64.rpm

**Comment by ekasprzak** [comment]
@bernerdad awesome!
I've been testing it for a last couple of days in RHEL 8.7 and seems like it works correctly.

Let me know if you would like to me test some specific functions/options.

And thanks a lot for making it possible!

**Comment by bernerdad** [comment]
Glad it is working for you!  Nothing specific for you to test.  I'll close the issue, but please reopen if anything crops up that we need to look at.  Cheers!
