### ISSUE TITLE
WSTunnel does not work on Ubuntu

### ISSUE THREAD

**Issue by nimagp** [Windscribe/Desktop-App#66]
WSTunnel does not work on Mint 21 (basically Ubuntu 22.04), It works fine on Windows and other Linux distros.
The handshake is successful, seems like a DNS misconfiguration. 
![image](https://user-images.githubusercontent.com/71447191/201204783-23306a7c-3f10-4ca9-869c-aac7d68b8b50.png)
Someone could solve the same issue by setting DNS manager to automatic and in-app DNS to cloudflare, but that doesn't have any effect.

**Comment by bernerdad** [comment]
Please submit your diagnostic log to support by using the `Help->Send Debug Log` option in the app, then `Help->Send Ticket` to open a support ticket.  The diagnostic log will aid the devs in tracking down the issue.  Thanks!

**Comment by bernerdad** [comment]
Hi.  I tested v2.5.11 of the app on Ubuntu 22.04, and WSTunnel worked fine.  Are you running Windscribe app v2.5.11?  If not, you can obtain it by setting your update channel in the app to `Beta`, or download directly from:

https://deploy.totallyacdn.com/desktop-apps/2.5.11/windscribe_2.5.11_amd64.deb

**Comment by nimagp** [comment]
> Hi. I tested v2.5.11 of the app on Ubuntu 22.04, and WSTunnel worked fine. Are you running Windscribe app v2.5.11? If not, you can obtain it by setting your update channel in the app to `Beta`, or download directly from:
> 
> https://deploy.totallyacdn.com/desktop-apps/2.5.11/windscribe_2.5.11_amd64.deb

Thanks. seems like it only occurs in Iran. And it's not only Mint. But all ubuntu based distros. Works fine on Fedora and Windows. I opened a ticket

**Comment by bernerdad** [comment]
Hi.  Would you be able to let us know if this issue is still happening with our latest guinea pig build?  Thanks!
https://deploy.totallyacdn.com/desktop-apps/2.7.10/windscribe_2.7.10_guinea_pig_amd64.deb
