### ISSUE TITLE
Problem in connection

### ISSUE THREAD

**Issue by mehdifirefox** [Windscribe/Desktop-App#72]
Hello
Many people in Iran have this problem
The program will connect
But after a few seconds this error comes
The program is connected
But there is cut
https://easyupload.io/j6oni6
"We've detected that your network settings may interfere with Windscribe. Please disconnect and send us a Debug Log, by going into Preferences and clicking the "Send Log" button."

I already sent this notice through the program

**Comment by bernerdad** [comment]
Hi.  Thank you for submitting your debug log to our support team.  They'll troubleshoot the issue and escalate it to the development team if it appears to be a bug.

**Comment by mehdifirefox** [comment]
Thank you.
Only your protocol is free and it was working well these days.

People really need you to circulate information. If you update late... it
may be late forever

**Comment by kohu12** [comment]
Hi. Tell now I could not set up the program
Please help

**Comment by mehdifirefox** [comment]
A month passed
I installed the new version 2..6.5 alpha
But we still have trouble connecting
This problem is not just for me.
Many people in Iran have this problem
Please fix the problem

**Comment by bernerdad** [comment]
Hi.  The 2.7 stable build (2.7.14), available from the website, implements new anti-censorship measures.  Please let us know if they work for you.  You can enable them by going into `Preferences->Connection` and toggling `Circumvent Censorship` on.  Thanks!
