### ISSUE TITLE
Can't move main dialog around desktop

### ISSUE THREAD

**Issue by anfokaboom** [Windscribe/Desktop-App#73]
Hi
Using ZorinOS 16.2 (Ubuntu 20.04 fork). WS client is installed and functioning as expected, however, I am unable to move the dialog. It will allow me to interact with dialog functions, close to the tray and restore, just not move anywhere.

Occurs in both the Van Gogh (lol) and Alpha GUIs.

**Comment by bernerdad** [comment]
Hi.  I'm using ZorinOS 16.2 as my main Linux dev box.  I was able to replicate this issue if I enable 'Docked' mode in settings.  That mode is not currently working correctly when using the Wayland compositor.  Turn it off, if you have it on, and let us know if that rectifies the issue for you.  Cheers!

**Comment by anfokaboom** [comment]
Yes, toggling docked to 'off' does permit the dialogue to be moved.
