### ISSUE TITLE
IKEv2 Policy Question

### ISSUE THREAD

**Issue by aw1875** [Windscribe/Desktop-App#75]
Not sure if this is something that can be answered for me but figured I might as well ask. I'm currently working on a project of my own and had a question about something I found in your code. Currently, I've been setting the IKEv2 policies with a PowerShell command but I noticed that you guys are using the WritePrivateProfileString function from the windows API. My question was about [this line](https://github.com/Windscribe/Desktop-App/blob/94ee9bf691d729ade8253dfe9fb9fcc31f5b1b8f/backend/windows/windscribe_service/ikev2ipsec.cpp#L79). I was curious where you got the number string used as the third parameter. I currently use a different set of security policies and I haven't been able to find any documentation online on where this number comes from. If it's possible to answer this I really appreciate it.

Thanks!

P.S. Pretty much the only thing I need to modify is the IntegrityCheckMethod since I have mine setup to accept SHA384 instead of SHA256

**Comment by bernerdad** [comment]
Hi.  I'm not sure how that magic number was generated.  Take a look at the demo code starting at line 645 here (https://fossies.org/dox/brave-core-1.46.144/winvpntool_8cc_source.html).  That should help both of us decode that magic number.  Cheers!

**Comment by aw1875** [comment]
I actually found a quick workaround by setting my security policies via the command line like I had in the past and then manually grabbing the policy string from the phonebook. However, I appreciate you passing on that link as it helps a ton with understanding the process behind it and can be very useful moving forward if I decide to modify my policies on the server!
