### ISSUE TITLE
Can't connect and can't uninstall

### ISSUE THREAD

**Issue by RogerLacetania** [Windscribe/Desktop-App#77]
I downloaded the GUI option on the official page, the .deb package. Installed it but it throw some errors:

`roger-rius@rius-pc:~/Descargas$ sudo dpkg -i windscribe_2.5.18_amd64.deb 
Seleccionando el paquete windscribe previamente no seleccionado.
(Leyendo la base de datos ... 223024 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar windscribe_2.5.18_amd64.deb ...
Removed /etc/systemd/system/multi-user.target.wants/windscribe-helper.service.
rm: no se puede borrar '/usr/local/bin/windscribe-cli': No existe el archivo o el directorio
dpkg: atención: el subproceso antiguo paquete windscribe script pre-removal devolvió el código de salida de error 1
dpkg: probando el script del nuevo paquete en su lugar...
rm: no se puede borrar '/usr/local/bin/windscribe-cli': No existe el archivo o el directorio
dpkg: error al procesar el archivo windscribe_2.5.18_amd64.deb (--install):
 el subproceso nuevo paquete windscribe script pre-removal devolvió el código de salida de error 1
Created symlink /etc/systemd/system/multi-user.target.wants/windscribe-helper.service → /etc/systemd/system/windscribe-helper.service.
ln: fallo al crear el enlace simbólico '/usr/local/bin/windscribe-cli': No existe el archivo o el directorio
dpkg: error al limpiar:
 el subproceso instalado paquete windscribe script post-installation devolvió el código de salida de error 1
Se encontraron errores al procesar:
 windscribe_2.5.18_amd64.deb`

It installed wrongly but i can open the program and navigate on it but can't connect.
I tried reinstalling it but I still can't do it. Same error as above. Tried --purge and -r to remove it and still the same. Now i can't even use apt upgrade.

**Comment by bernerdad** [comment]
Please submit your diagnostic log to support by using the `Help->Send Debug Log` option in the app, then `Help->Send Ticket` to open a support ticket. The diagnostic log will aid us devs in tracking down the issue if the support team cannot resolve it for you. Thanks!
