### ISSUE TITLE
windscribe-helper.service doesn't start on OpenSUSE MicroOS

### ISSUE THREAD

**Issue by sith-on-mars** [Windscribe/Desktop-App#82]
OS: OpenSUSE MicroOS (an immutable OS, uses systemd)
App version: v2.6.12

Starting Windscribe was met with helper initialization error like [here](https://github.com/Windscribe/Desktop-App/issues/14). I found that for some reason, Windscribe couldn't manage to enable systemd service. So I had to manually enable systemd service `sudo systemctl enable windscribe-helper.service`.

So maybe Windscribe should make a launch script to enable systemd service?

**Comment by sith-on-mars** [comment]
Seems it's a common issue on immutable system. The discussion thread of Mullvad might be helpful: https://github.com/mullvad/mullvadvpn-app/issues/1570

**Comment by bernerdad** [comment]
Hi.  We do have a ticket on our board to investigate similar issues on Fedora Silverblue.  Unfortunately, it will likely be quite some time before we'll have resources available to investigate this, as they are not on or supported distros list.  Sorry!

**Comment by bernerdad** [comment]
@sith-on-mars If you're still using this OS, could you let us know if the latest guinea pig [build](https://github.com/Windscribe/Desktop-App/releases/tag/v2.11.6) resolves the issue.  Thank you!
