### ISSUE TITLE
Windscribe firewall always working on even turning off

### ISSUE THREAD

**Issue by sith-on-mars** [Windscribe/Desktop-App#83]
OS: OpenSUSE MicroOS Gnome (an immutable OS, uses systemd)
App version: v2.6.12

I found that as soon as you start the app, the firewall is always working even you turn it off. I tried to switch to automatic mode, turn off the connection and manually turn off the firewall, but I still couldn't connect the internet. It is the same case even if I quitted the app with automatic mode.

**Comment by sith-on-mars** [comment]
Thank you! Could you send me the rpm file? OpenSUSE uses the rpm format.

**Comment by bernerdad** [comment]
Doh!  Apologies for my brain fart.  Here's the rpm:
https://deploy.totallyacdn.com/desktop-apps/2.6.14/windscribe_2.6.14_x86_64.rpm

**Comment by sith-on-mars** [comment]
New issue was fixed by the new version! Thank you so much for the fix.
