### ISSUE TITLE
Remember last Locations tab between sessions

### ISSUE THREAD

**Issue by ltguillaume** [Windscribe/Desktop-App#87]
I only click the Locations button to go to my favorites, but between sessions/reboots, the active tab is not remembered. In contrast, the Android app (at least the old version without any Google junk in it I'm using, 2.4.1.491) does remember and it's so much nicer to use.

So, I'd like to propose the same behavior for the desktop app.

**Comment by bernerdad** [comment]
Which platform are you on, and is this with the latest guinea pig (v2.7.9) build?

**Comment by ltguillaume** [comment]
2.7.9 on W10.

**Comment by bernerdad** [comment]
Please let us know if this issue is resolved in the just released 2.7.10 build.  Thanks!

**Comment by ltguillaume** [comment]
I can't test 2.7.10 because a DNS issue introduced by it: #104

**Comment by bernerdad** [comment]
Hmmm... this one is a head scratch-er.  None of us are able to replicate this behavior and nothing jumped out at us during code inspection.  If you notice any details indicating the bug only occurs under a certain set of circumstances, please let us know so we can better track this down.  Thanks!

**Comment by bernerdad** [comment]
> @bernerdad This issue has just gotten worse: as soon as I click a server to connect to it, or to star it, in the ALL tab, I'll often just be sent to the CONFIGURED tab for no reason.
> 
> v2.9.4

Thanks for the update!  This bizarre behavior still has us devs and QA puzzled.  This area of the code looks correct, and we cannot reproduce this behavior, but we'll keep our eyes on it.
