### ISSUE TITLE
Failed to install CLI package on Devuan due to systemd dependency

### ISSUE THREAD

**Issue by teotikalki** [Windscribe/Desktop-App#89]
Action: 'sudo dpkg -i windscribe_2.6.14_amd64.deb'
Expcted result: software installs
Actual result: software fails to install, can't be uninstalled, and leaves dpkg in an unclean state
Note: My init system is 'runit'

This was tragically annoying. The install failed and then uninstalling ALSO failed. I had to manually edit '/var/lib/dpkg/info/windscribe.postinst'  and '/var/lib/dpkg/info/windscribe.prerm' and comment out the systemctl lines to even run 'dpkg -P'.

PLEASE don't hardcode systemd dependecies!

**Comment by Gojkira** [comment]
Also not unable to install while using runit on Artix. I understand that non-systemd Linux distros are an after thought of an after thought but I have not had this issue with other VPN software that put even less effort in supporting Linux.
