### ISSUE TITLE
Release arm64 (Apple Silicon) installer and application

### ISSUE THREAD

**Issue by jonaharagon** [Windscribe/Desktop-App#9]
Will a native Apple Silicon desktop application be released? The current download requires Rosetta.

**Comment by bernerdad** [comment]
Hi.  We have it on our board to investigate building the app for Apple's M1 platform.  Doing so will require we update from Qt 5.12.11 to 6.2, which is a fairly major change.  Stay tuned!

**Comment by bernerdad** [comment]
Happy to report we finally have a fully functioning Apple arm64 build.  A macOS universal binary should be available in our guinea pig channel, hopefully, by the end of the month.

**Comment by bernerdad** [comment]
Hi.  v2.5.6 is available in our guinea pig channel, and is a universal binary for macOS.  Cheers!
