### ISSUE TITLE
Mac update fails from app and disables internet

### ISSUE THREAD

**Issue by maxwell108** [Windscribe/Desktop-App#90]
Mac update fails from app and disables internet 
solution to restart wind scribe and close properly
download manualy and install

**Comment by bernerdad** [comment]
Hi.  Which version of the app were you updating to?  The current stable release (2.6.14) or the latest guinea pig build (2.7.3)?

**Comment by maxwell108** [comment]
yes stable 2.6.14-1

**Comment by bernerdad** [comment]
Should be resolved in the v2.7.12 beta available now.  Please reopen ticket if it is not.
