### ISSUE TITLE
SpoolSrv blocked by firewall while LAN traffic allowed

### ISSUE THREAD

**Issue by ltguillaume** [Windscribe/Desktop-App#92]
This might cause some lingering issues with networked printers (I remember quite a few older topics on Reddit about this).
```
User: ‎NT AUTHORITY\SYSTEM
Path: C:\windows\system32\spoolsv.exe
To IP: 192.168.1.12
To Port: 161 (snmp)
Protocol: udp
WFP layer: FWPM_LAYER_ALE_AUTH_CONNECT_V4
Filter name: WindscribeFirewall
Direction: Outbound
State: Blocked
```

Windscribe v2.7.5 on W10 x64

**Comment by bernerdad** [comment]
Thanks for the bug report!  We've added it to our internal board for resolution in the current milestone.

**Comment by bernerdad** [comment]
Hi.  Are you still able to reproduce this with the latest stable build (2.7.14) and the Allow LAN Traffic setting enabled?

**Comment by bernerdad** [comment]
Okay, that is what we are seeing as well.  SpoolSrv outbound requests are being correctly blocked and local LAN printing works fine.  We're going to close this one as resolved.  Will reopen if someone finds LAN printing is not working.  Cheers!
