### ISSUE TITLE
Unable to use local DNS due to app binding route to VPN interface

### ISSUE THREAD

**Issue by RainmakerRaw** [Windscribe/Desktop-App#93]
Tested on macOS Monterrey 12.6.7 using Windscribe 2.6.14. 

It appears impossible to use a local DNS server as the custom DNS in the app. I run AdGuard Home (v0.107.33 on Debian 12), and Knot Resolver (v5.6.0 on RHEL 9.2) on two local servers. Both servers block ads and trackers etc using a custom config and Hagezi's DNS blocklists, and are internet-accessible (DoH3, DoT and DoQ only, not :53 - which is only accessible locally). These servers redirect queries for my homelab (domains, services, etc) to another internal DNS. As such, I want to continue using them with the VPN. 

I noticed when setting custom DNS to the local server IPs (`10.100.0.152` and `10.100.0.153`) that Windscribe's app pops up to say the network settings are incompatible. The app turns green and shows connected, but the WAN IP doesn't change, and there's no Internet connectivity. Debug logging shows that a route was added forcing the custom DNS IP out through the `ipsec0` VPN interface: 

```
G [080723 11:44:49:724    116.719] [ikev2]	 Connection status changed: NEVPNStatusConnected
S [080723 11:44:50:000] [service]	 isConnected: 1, protocol: 28672
S [080723 11:44:50:000] [service]	 execute: route add -net 0.0.0.0 10.100.0.1 -ifscope en0
S [080723 11:44:50:000] [service]	 execute: route -q -n add -inet 10.255.255.0/24 -interface ipsec0
S [080723 11:44:50:000] [service]	 execute: route -q -n add -inet 10.100.0.153/32 -interface ipsec0
S [080723 11:44:50:000] [service]	 cmd: route add -net 10.100.0.0/24 10.100.0.1
S [080723 11:44:50:000] [service]	 cmd: route add -net [WAN_IP] 10.100.0.1
G [080723 11:44:50:026    117.022] [connection]	 ConnectionManager::onConnectionConnected(), state_ = 1
G [080723 11:44:50:027    117.022] [connection]	 VPN adapter and gateway: "adapter name = ipsec0; adapter IP = 10.172.151.126; gateway IP = ; remote IP = ; dns = (10.255.255.3); ifIndex = not detected"
G [080723 11:44:50:027    117.022] [connection]	 Custom DNS detected, will override with:  "10.100.0.153"
G [080723 11:44:50:027    117.022] [basic]	 FirewallController_mac::setInterfaceToSkip_posix -> "ipsec0"
G [080723 11:44:50:243    117.238] [connected_dns]	 Applying custom 'while connected' DNS change to network services:  QList("State:/Network/Service/F407B8BA-16CD-4F1A-B578-6942A16F5EAB/DNS")
G [080723 11:44:50:244    117.239] [packet_size]	 Packet size mode auto - using default MTU (Engine)
G [080723 11:44:50:244    117.239] [basic]	 Changed DNS servers for DnsResolver to OS default
G [080723 11:44:50:244    117.239] [connection]	 TestVPNTunnel::startTests()
G [080723 11:44:50:244    117.239] [connection]	 Doing tunnel test 1
G [080723 11:44:50:244    117.239] [server_api]	 Do ping test with timeout:  2000
G [080723 11:44:52:279    119.274] [network]	 Could not resolve "checkip.windscribe.com" (servers: QList() ): 12
G [080723 11:44:52:280    119.275] [server_api]	 "API request PingTest failed:" "DnsResolveError"
G [080723 11:44:52:280    119.275] [connection]	 Tunnel test  "1" failed
```

The route forcing the custom DNS over `ipsec0` (`route -q -n add -inet 10.100.0.153/32 -interface ipsec0`) breaks connectivity, and takes precedence over the main LAN route (`route add -net 10.100.0.0/24 10.100.0.1`). I have tried with and without the firewall (`pf`) active, and with and without split tunnelling active (to exclude my WAN IP and LAN subnet), as well as trying connecting and then quickly deleting the route manually in terminal; but it still doesn't allow the VPN to work.

When custom DNS is set to an RFC1918 address, I would suggest this route should not be added. I submitted ticket #2808044 about this before I found your Git.

**Comment by bernerdad** [comment]
Hi.  Please try our v2.7.6 alpha release and let us know if it resolves the issue for you:
https://windscribe.com/changelog/mac

**Comment by RainmakerRaw** [comment]
Dang, you guys work fast. This build works, thanks!!

**Comment by bernerdad** [comment]
Excellent, glad that build works for you.  Yes, the Linux and Windows v2.7.6 builds allow local DNS in a similar way.  Cheers!
