### ISSUE TITLE
Mouse input does not work in Wayland

### ISSUE THREAD

**Issue by ItzDerock** [Windscribe/Desktop-App#95]
## Details
Title says it all, clicking on buttons do not work, basically no reaction to mouse input from the app. 

![image](https://github.com/Windscribe/Desktop-App/assets/14848722/a4cb7ea7-632a-48b2-a277-54d9f88b2fe6)
System details and app version can be found in that screenshot. Running Hyprland as my WM. 

I cannot click anywhere in the app, except the scrollbar here:
![image](https://github.com/Windscribe/Desktop-App/assets/14848722/a78f6b7d-398c-4e8b-853c-b419472977ab)

## Workarounds
- Starting the app with `WAYLAND_DISPLAY= windscribe` works as this forces the app to use xwayland. 
- You can also use keyboard commands to somewhat navigate around. Press enter to log in when on getting started page. Use tab to move between fields and enter to submit. Hit space to show menu of regions and enter to connect.

**Comment by jaxu** [comment]
This doesn't seem to be a `wayland` issue per se, but something specifically with the Hyprland compositor.  I've added a ticket to investigate further for the next release.

**Comment by bernerdad** [comment]
Hi.  Can you let us know if our latest 2.8 guinea pig release resolves this issue?  Thanks!
https://deploy.totallyacdn.com/desktop-apps/2.8.2/windscribe_2.8.2_guinea_pig_x86_64.pkg.tar.zst

**Comment by ItzDerock** [comment]
@bernerdad that release seems to work great! There's just a few small visual bugs, but everything functions and I am able to use it just fine. Fixing the visual bugs would just be a QoL improvement, but not necessary since they don't affect usability that much.

https://github.com/Windscribe/Desktop-App/assets/14848722/5918947b-7661-40bc-9429-a53a0fb48012

**Comment by bernerdad** [comment]
Glad the new release fixed the mouse input problem for you!  It looks like the visual bugs are due to our widget toolkit (Qt 6.5).  We'll monitor Qt releases for any updates that might resolve this.  I'm going to close this issue as resolved.  Please feel free to open a new issue to track and address the visual bugs if you feel it is warranted.  Cheers!
